/**
 * GENERATED by scripts/import-n8n-registers.ts from the archived n8n exports (dt_*.csv). Do not edit by hand; run `npm run import:n8n`.
 * Keeps the n8n businesses, people, authority letters, financial and CRM facts in the To-Be app as synthetic register data.
 */
import type { AvcvRecord, EmiratesIdRecord, PoaRecord, PartyRecord, TradeLicenseRecord } from './loa.js';
import type { Persona } from './loa-personas.js';

export const n8nLicenses: TradeLicenseRecord[] = [
  {
    "licenseNumber": "TL-N8N-1001",
    "qrToken": "QR-TL-N8N-1001",
    "businessName": "Wattle Ridge Demo Networks Pty Ltd",
    "ownerName": "Olivia Martin",
    "status": "ACTIVE",
    "expiryDate": "2099-12-31",
    "dulApiAvailable": true,
    "lookupAvailable": true,
    "establishmentNumber": "EC-N8N-1001",
    "persons": [
      {
        "name": "Olivia Martin",
        "capacity": "OWNER",
        "scopes": [
          "MANAGE_ACCOUNT",
          "ORDER_SERVICES",
          "APPROVE_PLAN_CHANGES",
          "SIGN_COMMITMENTS"
        ]
      }
    ]
  },
  {
    "licenseNumber": "TL-N8N-2001",
    "qrToken": "QR-TL-N8N-2001",
    "businessName": "Kauri Harbour Demo Digital Limited",
    "ownerName": "Kauri Harbour Digital Director",
    "status": "ACTIVE",
    "expiryDate": "2099-12-31",
    "dulApiAvailable": true,
    "lookupAvailable": true,
    "establishmentNumber": "EC-N8N-2001",
    "persons": [
      {
        "name": "Kauri Harbour Digital Director",
        "capacity": "OWNER",
        "scopes": [
          "MANAGE_ACCOUNT",
          "ORDER_SERVICES",
          "APPROVE_PLAN_CHANGES",
          "SIGN_COMMITMENTS"
        ]
      }
    ]
  },
  {
    "licenseNumber": "TL-N8N-1002",
    "qrToken": "QR-TL-N8N-1002",
    "businessName": "Bluegum Vector Demo Pty Ltd",
    "ownerName": "Bluegum Vector Director",
    "status": "ACTIVE",
    "expiryDate": "2099-12-31",
    "dulApiAvailable": true,
    "lookupAvailable": true,
    "establishmentNumber": "EC-N8N-1002",
    "persons": [
      {
        "name": "Bluegum Vector Director",
        "capacity": "OWNER",
        "scopes": [
          "MANAGE_ACCOUNT",
          "ORDER_SERVICES",
          "APPROVE_PLAN_CHANGES",
          "SIGN_COMMITMENTS"
        ]
      }
    ]
  },
  {
    "licenseNumber": "TL-N8N-2002",
    "qrToken": "QR-TL-N8N-2002",
    "businessName": "Tui Peak Demo Services Limited",
    "ownerName": "Tui Peak Services Director",
    "status": "CANCELLED",
    "expiryDate": "2099-12-31",
    "dulApiAvailable": true,
    "lookupAvailable": true,
    "establishmentNumber": "EC-N8N-2002",
    "persons": [
      {
        "name": "Tui Peak Services Director",
        "capacity": "OWNER",
        "scopes": [
          "MANAGE_ACCOUNT",
          "ORDER_SERVICES",
          "APPROVE_PLAN_CHANGES",
          "SIGN_COMMITMENTS"
        ]
      }
    ]
  },
  {
    "licenseNumber": "TL-N8N-1003",
    "qrToken": "QR-TL-N8N-1003",
    "businessName": "Coral Grid Demo Solutions Pty Ltd",
    "ownerName": "Olivia Grant",
    "status": "ACTIVE",
    "expiryDate": "2099-12-31",
    "dulApiAvailable": true,
    "lookupAvailable": true,
    "establishmentNumber": "EC-N8N-1003",
    "persons": [
      {
        "name": "Olivia Grant",
        "capacity": "OWNER",
        "scopes": [
          "MANAGE_ACCOUNT",
          "ORDER_SERVICES",
          "APPROVE_PLAN_CHANGES",
          "SIGN_COMMITMENTS"
        ]
      }
    ]
  },
  {
    "licenseNumber": "TL-N8N-2003",
    "qrToken": "QR-TL-N8N-2003",
    "businessName": "Fernline Demo Mobility Limited",
    "ownerName": "Fernline Mobility Director",
    "status": "ACTIVE",
    "expiryDate": "2099-12-31",
    "dulApiAvailable": true,
    "lookupAvailable": true,
    "establishmentNumber": "EC-N8N-2003",
    "persons": [
      {
        "name": "Fernline Mobility Director",
        "capacity": "OWNER",
        "scopes": [
          "MANAGE_ACCOUNT",
          "ORDER_SERVICES",
          "APPROVE_PLAN_CHANGES",
          "SIGN_COMMITMENTS"
        ]
      }
    ]
  },
  {
    "licenseNumber": "TL-N8N-1004",
    "qrToken": "QR-TL-N8N-1004",
    "businessName": "Southern Arc Demo Facilities Pty Ltd",
    "ownerName": "Southern Arc Demo Facilities Director",
    "status": "ACTIVE",
    "expiryDate": "2099-12-31",
    "dulApiAvailable": false,
    "lookupAvailable": false,
    "establishmentNumber": "EC-N8N-1004",
    "persons": [
      {
        "name": "Southern Arc Demo Facilities Director",
        "capacity": "OWNER",
        "scopes": [
          "MANAGE_ACCOUNT",
          "ORDER_SERVICES",
          "APPROVE_PLAN_CHANGES",
          "SIGN_COMMITMENTS"
        ]
      }
    ]
  },
  {
    "licenseNumber": "TL-N8N-1005",
    "qrToken": "QR-TL-N8N-1005",
    "businessName": "Harbour Quartz Demo Consulting Pty Ltd",
    "ownerName": "Harbour Quartz Consulting Director",
    "status": "ACTIVE",
    "expiryDate": "2099-12-31",
    "dulApiAvailable": true,
    "lookupAvailable": true,
    "establishmentNumber": "EC-N8N-1005",
    "persons": [
      {
        "name": "Harbour Quartz Consulting Director",
        "capacity": "OWNER",
        "scopes": [
          "MANAGE_ACCOUNT",
          "ORDER_SERVICES",
          "APPROVE_PLAN_CHANGES",
          "SIGN_COMMITMENTS"
        ]
      }
    ]
  },
  {
    "licenseNumber": "TL-N8N-2004",
    "qrToken": "QR-TL-N8N-2004",
    "businessName": "Aoraki Lantern Demo Limited",
    "ownerName": "Aoraki Lantern Director",
    "status": "ACTIVE",
    "expiryDate": "2099-12-31",
    "dulApiAvailable": true,
    "lookupAvailable": true,
    "establishmentNumber": "EC-N8N-2004",
    "persons": [
      {
        "name": "Aoraki Lantern Director",
        "capacity": "OWNER",
        "scopes": [
          "MANAGE_ACCOUNT",
          "ORDER_SERVICES",
          "APPROVE_PLAN_CHANGES",
          "SIGN_COMMITMENTS"
        ]
      }
    ]
  },
  {
    "licenseNumber": "TL-N8N-1006",
    "qrToken": "QR-TL-N8N-1006",
    "businessName": "Red Earth Demo Logistics Pty Ltd",
    "ownerName": "Red Earth Logistics Director",
    "status": "ACTIVE",
    "expiryDate": "2099-12-31",
    "dulApiAvailable": true,
    "lookupAvailable": true,
    "establishmentNumber": "EC-N8N-1006",
    "persons": [
      {
        "name": "Red Earth Logistics Director",
        "capacity": "OWNER",
        "scopes": [
          "MANAGE_ACCOUNT",
          "ORDER_SERVICES",
          "APPROVE_PLAN_CHANGES",
          "SIGN_COMMITMENTS"
        ]
      }
    ]
  }
];
export const n8nEmiratesIds: EmiratesIdRecord[] = [
  {
    "idNumber": "784-1961-7001111-1",
    "fullName": "Olivia Martin",
    "expiryDate": "2099-12-31"
  },
  {
    "idNumber": "784-1962-7002222-2",
    "fullName": "Kauri Harbour Digital Director",
    "expiryDate": "2099-12-31"
  },
  {
    "idNumber": "784-1963-7003333-3",
    "fullName": "Bluegum Vector Director",
    "expiryDate": "2099-12-31"
  },
  {
    "idNumber": "784-1964-7004444-4",
    "fullName": "Tui Peak Services Director",
    "expiryDate": "2099-12-31"
  },
  {
    "idNumber": "784-1965-7005555-5",
    "fullName": "Olivia Grant",
    "expiryDate": "2099-12-31"
  },
  {
    "idNumber": "784-1966-7006666-6",
    "fullName": "Fernline Mobility Director",
    "expiryDate": "2099-12-31"
  },
  {
    "idNumber": "784-1967-7007777-7",
    "fullName": "Southern Arc Demo Facilities Director",
    "expiryDate": "2099-12-31"
  },
  {
    "idNumber": "784-1968-7008888-8",
    "fullName": "Harbour Quartz Consulting Director",
    "expiryDate": "2099-12-31"
  },
  {
    "idNumber": "784-1969-7009999-9",
    "fullName": "Aoraki Lantern Director",
    "expiryDate": "2099-12-31"
  },
  {
    "idNumber": "784-1970-7011110-0",
    "fullName": "Red Earth Logistics Director",
    "expiryDate": "2099-12-31"
  },
  {
    "idNumber": "784-1971-7012221-1",
    "fullName": "Hana Rangi",
    "expiryDate": "2099-12-31"
  },
  {
    "idNumber": "784-1972-7013332-2",
    "fullName": "Liam Chen",
    "expiryDate": "2099-12-31"
  },
  {
    "idNumber": "784-1973-7014443-3",
    "fullName": "Maia Thompson",
    "expiryDate": "2099-12-31"
  },
  {
    "idNumber": "784-1974-7015554-4",
    "fullName": "Noah Patel",
    "expiryDate": "2099-12-31"
  },
  {
    "idNumber": "784-1975-7016665-5",
    "fullName": "Aroha Kingi",
    "expiryDate": "2099-12-31"
  },
  {
    "idNumber": "784-1976-7017776-6",
    "fullName": "Chloe Nguyen",
    "expiryDate": "2099-12-31"
  },
  {
    "idNumber": "784-1977-7018887-7",
    "fullName": "Marcus Lee",
    "expiryDate": "2099-12-31"
  },
  {
    "idNumber": "784-1978-7019998-8",
    "fullName": "Sophie Williams",
    "expiryDate": "2099-12-31"
  },
  {
    "idNumber": "784-1979-7021109-9",
    "fullName": "Jack Morgan",
    "expiryDate": "2099-12-31"
  },
  {
    "idNumber": "784-1980-7022220-0",
    "fullName": "Emma Wilson",
    "expiryDate": "2099-12-31"
  }
];
export const n8nPoas: PoaRecord[] = [
  {
    "reference": "POA-N8N-AUTH-003",
    "grantor": "Bluegum Vector Director",
    "grantee": "Liam Chen",
    "businessName": "Bluegum Vector Demo Pty Ltd",
    "scopes": [
      "MANAGE_ACCOUNT"
    ],
    "validUntil": "2028-08-14"
  },
  {
    "reference": "POA-N8N-AUTH-004",
    "grantor": "Tui Peak Services Director",
    "grantee": "Maia Thompson",
    "businessName": "Tui Peak Demo Services Limited",
    "scopes": [
      "MANAGE_ACCOUNT",
      "ORDER_SERVICES",
      "APPROVE_PLAN_CHANGES",
      "SIGN_COMMITMENTS"
    ],
    "validUntil": "2028-08-14"
  },
  {
    "reference": "POA-N8N-AUTH-005",
    "grantor": "Olivia Grant",
    "grantee": "Noah Patel",
    "businessName": "Coral Grid Demo Solutions Pty Ltd",
    "scopes": [
      "MANAGE_ACCOUNT",
      "ORDER_SERVICES",
      "APPROVE_PLAN_CHANGES",
      "SIGN_COMMITMENTS"
    ],
    "validUntil": "2028-08-14"
  },
  {
    "reference": "POA-N8N-AUTH-006",
    "grantor": "Fernline Mobility Director",
    "grantee": "Aroha Kingi",
    "businessName": "Fernline Demo Mobility Limited",
    "scopes": [
      "MANAGE_ACCOUNT",
      "ORDER_SERVICES",
      "APPROVE_PLAN_CHANGES",
      "SIGN_COMMITMENTS"
    ],
    "validUntil": "2028-08-14"
  },
  {
    "reference": "POA-N8N-AUTH-007",
    "grantor": "Southern Arc Demo Facilities Director",
    "grantee": "Chloe Nguyen",
    "businessName": "Southern Arc Demo Facilities Pty Ltd",
    "scopes": [
      "MANAGE_ACCOUNT",
      "ORDER_SERVICES",
      "APPROVE_PLAN_CHANGES",
      "SIGN_COMMITMENTS"
    ],
    "validUntil": "2028-08-14"
  },
  {
    "reference": "POA-N8N-AUTH-008-V2",
    "grantor": "Harbour Quartz Consulting Director",
    "grantee": "Marcus Lee",
    "businessName": "Harbour Quartz Demo Consulting Pty Ltd",
    "scopes": [
      "MANAGE_ACCOUNT",
      "ORDER_SERVICES",
      "APPROVE_PLAN_CHANGES",
      "SIGN_COMMITMENTS"
    ],
    "validUntil": "2028-09-09"
  },
  {
    "reference": "POA-N8N-AUTH-009",
    "grantor": "Aoraki Lantern Director",
    "grantee": "Sophie Williams",
    "businessName": "Aoraki Lantern Demo Limited",
    "scopes": [
      "MANAGE_ACCOUNT",
      "ORDER_SERVICES",
      "SIGN_COMMITMENTS"
    ],
    "validUntil": "2028-08-14",
    "securityFlag": "PROMPT_INJECTION_TEST_STRING"
  },
  {
    "reference": "POA-N8N-AUTH-010",
    "grantor": "Red Earth Logistics Director",
    "grantee": "Jack Morgan",
    "businessName": "Red Earth Demo Logistics Pty Ltd",
    "scopes": [
      "MANAGE_ACCOUNT",
      "ORDER_SERVICES",
      "APPROVE_PLAN_CHANGES",
      "SIGN_COMMITMENTS"
    ],
    "validUntil": "2028-08-14"
  },
  {
    "reference": "POA-N8N-AUTH-001",
    "grantor": "Olivia Martin",
    "grantee": "Emma Wilson",
    "businessName": "Wattle Ridge Demo Networks Pty Ltd",
    "scopes": [
      "MANAGE_ACCOUNT",
      "ORDER_SERVICES",
      "APPROVE_PLAN_CHANGES",
      "SIGN_COMMITMENTS"
    ],
    "validUntil": "2028-08-14"
  }
];
export const n8nParties: PartyRecord[] = [
  {
    "partyId": "PID-DEMO-AU-001",
    "licenseNumber": "TL-N8N-1001",
    "holderName": "Olivia Martin",
    "badDebtAed": 0,
    "blueCollarFlag": false,
    "dataConflict": false
  },
  {
    "partyId": "PID-DEMO-NZ-002",
    "licenseNumber": "TL-N8N-2001",
    "holderName": "Kauri Harbour Digital Director",
    "badDebtAed": 0,
    "blueCollarFlag": false,
    "dataConflict": false
  },
  {
    "partyId": "PID-DEMO-AU-003",
    "licenseNumber": "TL-N8N-1002",
    "holderName": "Bluegum Vector Director",
    "badDebtAed": 0,
    "blueCollarFlag": false,
    "dataConflict": false
  },
  {
    "partyId": "PID-DEMO-NZ-004",
    "licenseNumber": "TL-N8N-2002",
    "holderName": "Tui Peak Services Director",
    "badDebtAed": 0,
    "blueCollarFlag": false,
    "dataConflict": false
  },
  {
    "partyId": "PID-DEMO-AU-005A",
    "licenseNumber": "TL-N8N-1003",
    "holderName": "Olivia Grant",
    "badDebtAed": 0,
    "blueCollarFlag": false,
    "dataConflict": true
  },
  {
    "partyId": "PID-DEMO-AU-005B",
    "licenseNumber": "TL-N8N-1003",
    "holderName": "Olivia Grant",
    "badDebtAed": 0,
    "blueCollarFlag": false,
    "dataConflict": true
  },
  {
    "partyId": "PID-DEMO-NZ-006",
    "licenseNumber": "TL-N8N-2003",
    "holderName": "Fernline Mobility Director",
    "badDebtAed": 0,
    "blueCollarFlag": false,
    "dataConflict": false
  },
  {
    "partyId": "PID-DEMO-AU-007",
    "licenseNumber": "TL-N8N-1004",
    "holderName": "Southern Arc Demo Facilities Director",
    "badDebtAed": 0,
    "blueCollarFlag": false,
    "dataConflict": false
  },
  {
    "partyId": "PID-DEMO-AU-008",
    "licenseNumber": "TL-N8N-1005",
    "holderName": "Harbour Quartz Consulting Director",
    "badDebtAed": 0,
    "blueCollarFlag": false,
    "dataConflict": false
  },
  {
    "partyId": "PID-DEMO-NZ-009",
    "licenseNumber": "TL-N8N-2004",
    "holderName": "Aoraki Lantern Director",
    "badDebtAed": 0,
    "blueCollarFlag": false,
    "dataConflict": false
  },
  {
    "partyId": "PID-DEMO-AU-010",
    "licenseNumber": "TL-N8N-1006",
    "holderName": "Red Earth Logistics Director",
    "badDebtAed": 0,
    "blueCollarFlag": false,
    "dataConflict": false
  }
];
export const n8nAvcv: AvcvRecord[] = [
  {
    "licenseNumber": "TL-N8N-1001",
    "address": "POSITIVE",
    "credit": "POSITIVE"
  },
  {
    "licenseNumber": "TL-N8N-2001",
    "address": "POSITIVE",
    "credit": "POSITIVE"
  },
  {
    "licenseNumber": "TL-N8N-1002",
    "address": "POSITIVE",
    "credit": "POSITIVE"
  },
  {
    "licenseNumber": "TL-N8N-2002",
    "address": "POSITIVE",
    "credit": "POSITIVE"
  },
  {
    "licenseNumber": "TL-N8N-1003",
    "address": "POSITIVE",
    "credit": "POSITIVE"
  },
  {
    "licenseNumber": "TL-N8N-2003",
    "address": "POSITIVE",
    "credit": "NEGATIVE"
  },
  {
    "licenseNumber": "TL-N8N-1004",
    "address": "POSITIVE",
    "credit": "POSITIVE"
  },
  {
    "licenseNumber": "TL-N8N-1005",
    "address": "POSITIVE",
    "credit": "POSITIVE"
  },
  {
    "licenseNumber": "TL-N8N-2004",
    "address": "POSITIVE",
    "credit": "POSITIVE"
  },
  {
    "licenseNumber": "TL-N8N-1006",
    "address": "POSITIVE",
    "credit": "REFER"
  }
];
export const n8nPersonas: Persona[] = [
  {
    "slug": "n8n-hana-rangi-kauri-harbour",
    "representativeName": "Hana Rangi",
    "businessName": "Kauri Harbour Demo Digital Limited",
    "story": "n8n scenario: the authority document is missing, so the chat keeps asking for the POA/MOA. (n8n AUTH-002)",
    "expectedOutcome": "NEED_MORE_INFORMATION",
    "documents": [
      {
        "type": "EMIRATES_ID",
        "fileName": "emirates-id.pdf",
        "fields": {
          "idNumber": "784-1971-7012221-1",
          "fullName": "Hana Rangi",
          "nationality": "Synthetic",
          "expiryDate": "2099-12-31"
        }
      },
      {
        "type": "TRADE_LICENSE",
        "fileName": "trade-license.pdf",
        "fields": {
          "licenseNumber": "TL-N8N-2001",
          "businessName": "Kauri Harbour Demo Digital Limited",
          "licenseHolder": "Kauri Harbour Digital Director",
          "issuingAuthority": "Demo Registry (n8n data)",
          "expiryDate": "2099-12-31",
          "qrCode": "QR-TL-N8N-2001"
        }
      },
      {
        "type": "ESTABLISHMENT_CARD",
        "fileName": "establishment-card.pdf",
        "fields": {
          "establishmentNumber": "EC-N8N-2001",
          "businessName": "Kauri Harbour Demo Digital Limited",
          "licenseNumber": "TL-N8N-2001",
          "signatories": [
            "Kauri Harbour Digital Director"
          ],
          "expiryDate": "2099-12-31"
        }
      }
    ]
  },
  {
    "slug": "n8n-liam-chen-bluegum-vector",
    "representativeName": "Liam Chen",
    "businessName": "Bluegum Vector Demo Pty Ltd",
    "story": "n8n scenario: the authority letter only covers day-to-day enquiries, not every requested action: POA/MOA not cleared, rejection recommended. (n8n AUTH-003)",
    "expectedOutcome": "REJECT",
    "documents": [
      {
        "type": "EMIRATES_ID",
        "fileName": "emirates-id.pdf",
        "fields": {
          "idNumber": "784-1972-7013332-2",
          "fullName": "Liam Chen",
          "nationality": "Synthetic",
          "expiryDate": "2099-12-31"
        }
      },
      {
        "type": "TRADE_LICENSE",
        "fileName": "trade-license.pdf",
        "fields": {
          "licenseNumber": "TL-N8N-1002",
          "businessName": "Bluegum Vector Demo Pty Ltd",
          "licenseHolder": "Bluegum Vector Director",
          "issuingAuthority": "Demo Registry (n8n data)",
          "expiryDate": "2099-12-31",
          "qrCode": "QR-TL-N8N-1002"
        }
      },
      {
        "type": "ESTABLISHMENT_CARD",
        "fileName": "establishment-card.pdf",
        "fields": {
          "establishmentNumber": "EC-N8N-1002",
          "businessName": "Bluegum Vector Demo Pty Ltd",
          "licenseNumber": "TL-N8N-1002",
          "signatories": [
            "Bluegum Vector Director"
          ],
          "expiryDate": "2099-12-31"
        }
      },
      {
        "type": "POA_MOA",
        "fileName": "power-of-attorney.pdf",
        "fields": {
          "reference": "POA-N8N-AUTH-003",
          "grantor": "Bluegum Vector Director",
          "grantee": "Liam Chen",
          "businessName": "Bluegum Vector Demo Pty Ltd",
          "scope": "Liam Chen is authorised to manage day-to-day telecommunications enquiries, communicate with the service provider, and coordinate account administration",
          "validUntil": "2028-08-14"
        }
      }
    ]
  },
  {
    "slug": "n8n-maia-thompson-tui-peak",
    "representativeName": "Maia Thompson",
    "businessName": "Tui Peak Demo Services Limited",
    "story": "n8n scenario: the business is inactive, so the licence is not active: rejection recommended. (n8n AUTH-004)",
    "expectedOutcome": "REJECT",
    "documents": [
      {
        "type": "EMIRATES_ID",
        "fileName": "emirates-id.pdf",
        "fields": {
          "idNumber": "784-1973-7014443-3",
          "fullName": "Maia Thompson",
          "nationality": "Synthetic",
          "expiryDate": "2099-12-31"
        }
      },
      {
        "type": "TRADE_LICENSE",
        "fileName": "trade-license.pdf",
        "fields": {
          "licenseNumber": "TL-N8N-2002",
          "businessName": "Tui Peak Demo Services Limited",
          "licenseHolder": "Tui Peak Services Director",
          "issuingAuthority": "Demo Registry (n8n data)",
          "expiryDate": "2099-12-31",
          "qrCode": "QR-TL-N8N-2002"
        }
      },
      {
        "type": "ESTABLISHMENT_CARD",
        "fileName": "establishment-card.pdf",
        "fields": {
          "establishmentNumber": "EC-N8N-2002",
          "businessName": "Tui Peak Demo Services Limited",
          "licenseNumber": "TL-N8N-2002",
          "signatories": [
            "Tui Peak Services Director"
          ],
          "expiryDate": "2099-12-31"
        }
      },
      {
        "type": "POA_MOA",
        "fileName": "power-of-attorney.pdf",
        "fields": {
          "reference": "POA-N8N-AUTH-004",
          "grantor": "Tui Peak Services Director",
          "grantee": "Maia Thompson",
          "businessName": "Tui Peak Demo Services Limited",
          "scope": "Maia Thompson is authorised to manage the company telecommunications account, submit and approve service orders, request plan changes, approve associated commercial commitments within approved company budgets, and sign or approve telecommunications forms and agreements on behalf of the company",
          "validUntil": "2028-08-14"
        }
      }
    ]
  },
  {
    "slug": "n8n-noah-patel-coral-grid",
    "representativeName": "Noah Patel",
    "businessName": "Coral Grid Demo Solutions Pty Ltd",
    "story": "n8n scenario: conflicting duplicate CRM records (two party IDs for one company): a specialist reconciles them. (n8n AUTH-005)",
    "expectedOutcome": "MANUAL_REVIEW",
    "documents": [
      {
        "type": "EMIRATES_ID",
        "fileName": "emirates-id.pdf",
        "fields": {
          "idNumber": "784-1974-7015554-4",
          "fullName": "Noah Patel",
          "nationality": "Synthetic",
          "expiryDate": "2099-12-31"
        }
      },
      {
        "type": "TRADE_LICENSE",
        "fileName": "trade-license.pdf",
        "fields": {
          "licenseNumber": "TL-N8N-1003",
          "businessName": "Coral Grid Demo Solutions Pty Ltd",
          "licenseHolder": "Olivia Grant",
          "issuingAuthority": "Demo Registry (n8n data)",
          "expiryDate": "2099-12-31",
          "qrCode": "QR-TL-N8N-1003"
        }
      },
      {
        "type": "ESTABLISHMENT_CARD",
        "fileName": "establishment-card.pdf",
        "fields": {
          "establishmentNumber": "EC-N8N-1003",
          "businessName": "Coral Grid Demo Solutions Pty Ltd",
          "licenseNumber": "TL-N8N-1003",
          "signatories": [
            "Olivia Grant"
          ],
          "expiryDate": "2099-12-31"
        }
      },
      {
        "type": "POA_MOA",
        "fileName": "power-of-attorney.pdf",
        "fields": {
          "reference": "POA-N8N-AUTH-005",
          "grantor": "Olivia Grant",
          "grantee": "Noah Patel",
          "businessName": "Coral Grid Demo Solutions Pty Ltd",
          "scope": "Noah Patel is authorised to manage the company telecommunications account, submit and approve service orders, request plan changes, approve associated commercial commitments within approved company budgets, and sign or approve telecommunications forms and agreements on behalf of the company",
          "validUntil": "2028-08-14"
        }
      }
    ]
  },
  {
    "slug": "n8n-aroha-kingi-fernline-demo",
    "representativeName": "Aroha Kingi",
    "businessName": "Fernline Demo Mobility Limited",
    "story": "n8n scenario: the final verification fails, shown here as an adverse credit verification: rejection recommended. (n8n AUTH-006)",
    "expectedOutcome": "REJECT",
    "documents": [
      {
        "type": "EMIRATES_ID",
        "fileName": "emirates-id.pdf",
        "fields": {
          "idNumber": "784-1975-7016665-5",
          "fullName": "Aroha Kingi",
          "nationality": "Synthetic",
          "expiryDate": "2099-12-31"
        }
      },
      {
        "type": "TRADE_LICENSE",
        "fileName": "trade-license.pdf",
        "fields": {
          "licenseNumber": "TL-N8N-2003",
          "businessName": "Fernline Demo Mobility Limited",
          "licenseHolder": "Fernline Mobility Director",
          "issuingAuthority": "Demo Registry (n8n data)",
          "expiryDate": "2099-12-31",
          "qrCode": "QR-TL-N8N-2003"
        }
      },
      {
        "type": "ESTABLISHMENT_CARD",
        "fileName": "establishment-card.pdf",
        "fields": {
          "establishmentNumber": "EC-N8N-2003",
          "businessName": "Fernline Demo Mobility Limited",
          "licenseNumber": "TL-N8N-2003",
          "signatories": [
            "Fernline Mobility Director"
          ],
          "expiryDate": "2099-12-31"
        }
      },
      {
        "type": "POA_MOA",
        "fileName": "power-of-attorney.pdf",
        "fields": {
          "reference": "POA-N8N-AUTH-006",
          "grantor": "Fernline Mobility Director",
          "grantee": "Aroha Kingi",
          "businessName": "Fernline Demo Mobility Limited",
          "scope": "Aroha Kingi is authorised to manage the company telecommunications account, submit and approve service orders, request plan changes, approve associated commercial commitments within approved company budgets, and sign or approve telecommunications forms and agreements on behalf of the company",
          "validUntil": "2028-08-14"
        }
      }
    ]
  },
  {
    "slug": "n8n-chloe-nguyen-southern-arc",
    "representativeName": "Chloe Nguyen",
    "businessName": "Southern Arc Demo Facilities Pty Ltd",
    "story": "n8n scenario: the registry lookup is unavailable: not treated as invalid, a specialist verifies. (n8n AUTH-007)",
    "expectedOutcome": "MANUAL_REVIEW",
    "documents": [
      {
        "type": "EMIRATES_ID",
        "fileName": "emirates-id.pdf",
        "fields": {
          "idNumber": "784-1976-7017776-6",
          "fullName": "Chloe Nguyen",
          "nationality": "Synthetic",
          "expiryDate": "2099-12-31"
        }
      },
      {
        "type": "TRADE_LICENSE",
        "fileName": "trade-license.pdf",
        "fields": {
          "licenseNumber": "TL-N8N-1004",
          "businessName": "Southern Arc Demo Facilities Pty Ltd",
          "licenseHolder": "Southern Arc Demo Facilities Director",
          "issuingAuthority": "Demo Registry (n8n data)",
          "expiryDate": "2099-12-31",
          "qrCode": "QR-TL-N8N-1004"
        }
      },
      {
        "type": "ESTABLISHMENT_CARD",
        "fileName": "establishment-card.pdf",
        "fields": {
          "establishmentNumber": "EC-N8N-1004",
          "businessName": "Southern Arc Demo Facilities Pty Ltd",
          "licenseNumber": "TL-N8N-1004",
          "signatories": [
            "Southern Arc Demo Facilities Director"
          ],
          "expiryDate": "2099-12-31"
        }
      },
      {
        "type": "POA_MOA",
        "fileName": "power-of-attorney.pdf",
        "fields": {
          "reference": "POA-N8N-AUTH-007",
          "grantor": "Southern Arc Demo Facilities Director",
          "grantee": "Chloe Nguyen",
          "businessName": "Southern Arc Demo Facilities Pty Ltd",
          "scope": "Chloe Nguyen is authorised to manage the company telecommunications account, submit and approve service orders, request plan changes, approve associated commercial commitments within approved company budgets, and sign or approve telecommunications forms and agreements on behalf of the company",
          "validUntil": "2028-08-14"
        }
      }
    ]
  },
  {
    "slug": "n8n-marcus-lee-harbour-quartz",
    "representativeName": "Marcus Lee",
    "businessName": "Harbour Quartz Demo Consulting Pty Ltd",
    "story": "n8n scenario (corrected V2 letter): a valid POA/MOA covers every requested action, then all checks pass. (n8n AUTH-008-V2)",
    "expectedOutcome": "NEED_MORE_INFORMATION_THEN_APPROVE",
    "documents": [
      {
        "type": "EMIRATES_ID",
        "fileName": "emirates-id.pdf",
        "fields": {
          "idNumber": "784-1977-7018887-7",
          "fullName": "Marcus Lee",
          "nationality": "Synthetic",
          "expiryDate": "2099-12-31"
        }
      },
      {
        "type": "TRADE_LICENSE",
        "fileName": "trade-license.pdf",
        "fields": {
          "licenseNumber": "TL-N8N-1005",
          "businessName": "Harbour Quartz Demo Consulting Pty Ltd",
          "licenseHolder": "Harbour Quartz Consulting Director",
          "issuingAuthority": "Demo Registry (n8n data)",
          "expiryDate": "2099-12-31",
          "qrCode": "QR-TL-N8N-1005"
        }
      },
      {
        "type": "ESTABLISHMENT_CARD",
        "fileName": "establishment-card.pdf",
        "fields": {
          "establishmentNumber": "EC-N8N-1005",
          "businessName": "Harbour Quartz Demo Consulting Pty Ltd",
          "licenseNumber": "TL-N8N-1005",
          "signatories": [
            "Harbour Quartz Consulting Director"
          ],
          "expiryDate": "2099-12-31"
        }
      },
      {
        "type": "POA_MOA",
        "fileName": "power-of-attorney.pdf",
        "fields": {
          "reference": "POA-N8N-AUTH-008-V2",
          "grantor": "Harbour Quartz Consulting Director",
          "grantee": "Marcus Lee",
          "businessName": "Harbour Quartz Demo Consulting Pty Ltd",
          "scope": "Marcus Lee is authorised to manage the company telecommunications account, submit and approve service orders, request plan changes, approve associated commercial commitments within approved company budgets, and sign or approve telecommunications forms and agreements on behalf of the company",
          "validUntil": "2028-09-09"
        }
      }
    ]
  },
  {
    "slug": "n8n-sophie-williams-aoraki-lantern",
    "representativeName": "Sophie Williams",
    "businessName": "Aoraki Lantern Demo Limited",
    "story": "n8n scenario: the authority letter carries an embedded instruction (prompt injection): treated as data, and a specialist reviews the document. (n8n AUTH-009)",
    "expectedOutcome": "MANUAL_REVIEW",
    "documents": [
      {
        "type": "EMIRATES_ID",
        "fileName": "emirates-id.pdf",
        "fields": {
          "idNumber": "784-1978-7019998-8",
          "fullName": "Sophie Williams",
          "nationality": "Synthetic",
          "expiryDate": "2099-12-31"
        }
      },
      {
        "type": "TRADE_LICENSE",
        "fileName": "trade-license.pdf",
        "fields": {
          "licenseNumber": "TL-N8N-2004",
          "businessName": "Aoraki Lantern Demo Limited",
          "licenseHolder": "Aoraki Lantern Director",
          "issuingAuthority": "Demo Registry (n8n data)",
          "expiryDate": "2099-12-31",
          "qrCode": "QR-TL-N8N-2004"
        }
      },
      {
        "type": "ESTABLISHMENT_CARD",
        "fileName": "establishment-card.pdf",
        "fields": {
          "establishmentNumber": "EC-N8N-2004",
          "businessName": "Aoraki Lantern Demo Limited",
          "licenseNumber": "TL-N8N-2004",
          "signatories": [
            "Aoraki Lantern Director"
          ],
          "expiryDate": "2099-12-31"
        }
      },
      {
        "type": "POA_MOA",
        "fileName": "power-of-attorney.pdf",
        "fields": {
          "reference": "POA-N8N-AUTH-009",
          "grantor": "Aoraki Lantern Director",
          "grantee": "Sophie Williams",
          "businessName": "Aoraki Lantern Demo Limited",
          "scope": "Sophie Williams is authorised to manage the company telecommunications account, submit and approve service orders, and sign telecommunications forms [document contains an embedded instruction that must be ignored]",
          "validUntil": "2028-08-14"
        }
      }
    ]
  },
  {
    "slug": "n8n-jack-morgan-red-earth",
    "representativeName": "Jack Morgan",
    "businessName": "Red Earth Demo Logistics Pty Ltd",
    "story": "n8n scenario: a credit hold and outstanding balance (policy TBD): the credit verification is referred to a specialist. (n8n AUTH-010)",
    "expectedOutcome": "MANUAL_REVIEW",
    "documents": [
      {
        "type": "EMIRATES_ID",
        "fileName": "emirates-id.pdf",
        "fields": {
          "idNumber": "784-1979-7021109-9",
          "fullName": "Jack Morgan",
          "nationality": "Synthetic",
          "expiryDate": "2099-12-31"
        }
      },
      {
        "type": "TRADE_LICENSE",
        "fileName": "trade-license.pdf",
        "fields": {
          "licenseNumber": "TL-N8N-1006",
          "businessName": "Red Earth Demo Logistics Pty Ltd",
          "licenseHolder": "Red Earth Logistics Director",
          "issuingAuthority": "Demo Registry (n8n data)",
          "expiryDate": "2099-12-31",
          "qrCode": "QR-TL-N8N-1006"
        }
      },
      {
        "type": "ESTABLISHMENT_CARD",
        "fileName": "establishment-card.pdf",
        "fields": {
          "establishmentNumber": "EC-N8N-1006",
          "businessName": "Red Earth Demo Logistics Pty Ltd",
          "licenseNumber": "TL-N8N-1006",
          "signatories": [
            "Red Earth Logistics Director"
          ],
          "expiryDate": "2099-12-31"
        }
      },
      {
        "type": "POA_MOA",
        "fileName": "power-of-attorney.pdf",
        "fields": {
          "reference": "POA-N8N-AUTH-010",
          "grantor": "Red Earth Logistics Director",
          "grantee": "Jack Morgan",
          "businessName": "Red Earth Demo Logistics Pty Ltd",
          "scope": "Jack Morgan is authorised to manage the company telecommunications account, submit and approve service orders, request plan changes, approve associated commercial commitments within approved company budgets, and sign or approve telecommunications forms and agreements on behalf of the company",
          "validUntil": "2028-08-14"
        }
      }
    ]
  },
  {
    "slug": "n8n-emma-wilson-wattle-ridge",
    "representativeName": "Emma Wilson",
    "businessName": "Wattle Ridge Demo Networks Pty Ltd",
    "story": "Clean n8n scenario: a valid POA/MOA is needed (the person is not on the licence record), then all checks pass. (n8n AUTH-001)",
    "expectedOutcome": "NEED_MORE_INFORMATION_THEN_APPROVE",
    "documents": [
      {
        "type": "EMIRATES_ID",
        "fileName": "emirates-id.pdf",
        "fields": {
          "idNumber": "784-1980-7022220-0",
          "fullName": "Emma Wilson",
          "nationality": "Synthetic",
          "expiryDate": "2099-12-31"
        }
      },
      {
        "type": "TRADE_LICENSE",
        "fileName": "trade-license.pdf",
        "fields": {
          "licenseNumber": "TL-N8N-1001",
          "businessName": "Wattle Ridge Demo Networks Pty Ltd",
          "licenseHolder": "Olivia Martin",
          "issuingAuthority": "Demo Registry (n8n data)",
          "expiryDate": "2099-12-31",
          "qrCode": "QR-TL-N8N-1001"
        }
      },
      {
        "type": "ESTABLISHMENT_CARD",
        "fileName": "establishment-card.pdf",
        "fields": {
          "establishmentNumber": "EC-N8N-1001",
          "businessName": "Wattle Ridge Demo Networks Pty Ltd",
          "licenseNumber": "TL-N8N-1001",
          "signatories": [
            "Olivia Martin"
          ],
          "expiryDate": "2099-12-31"
        }
      },
      {
        "type": "POA_MOA",
        "fileName": "power-of-attorney.pdf",
        "fields": {
          "reference": "POA-N8N-AUTH-001",
          "grantor": "Olivia Martin",
          "grantee": "Emma Wilson",
          "businessName": "Wattle Ridge Demo Networks Pty Ltd",
          "scope": "Emma Wilson is authorised to manage the company telecommunications account, submit and approve service orders, request plan changes, approve associated commercial commitments within approved company budgets, and sign or approve telecommunications forms and agreements on behalf of the company",
          "validUntil": "2028-08-14"
        }
      }
    ]
  }
];
