// Discovery generator: reads the preserved n8n exports and CSV data-table exports (read-only) and writes
//   docs/01-source-inventory.md, docs/02-workflow-graph.md, docs/03-node-catalog.md, docs/04-data-dictionary.md,
//   artifacts/source-node-catalog.json, artifacts/source-checksums.json.
// docs/05 is generated by `npm run docs:traceability`; docs/06-08 are maintained by hand.
import { createHash } from 'node:crypto';
import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { basename, extname, join, relative } from 'node:path';

const root = process.cwd();
const docsDir = join(root, 'docs');
const sourceExtensions = new Set(['.json', '.csv', '.txt', '.pdf', '.md']);
const ignoredDirectories = new Set(['.git', 'node_modules', 'apps', 'packages', 'artifacts', 'docs', 'coverage', 'dist', 'tests', 'scripts', 'types', 'scratch', 'uploads', 'test-results', 'playwright-report', '.claude']);
const bom = new RegExp(`^${String.fromCharCode(0xfeff)}`);

function sourceFiles(directory = root) {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const file = join(directory, entry.name);
    if (entry.isDirectory()) return ignoredDirectories.has(entry.name) ? [] : sourceFiles(file);
    // Only uploaded source artifacts: the n8n exports (numbered *.json) and dt_*.csv data-table exports.
    return (extname(entry.name).toLowerCase() === '.json' && /^\d/.test(entry.name)) || (extname(entry.name).toLowerCase() === '.csv' && entry.name.startsWith('dt_')) || (['.pdf', '.txt'].includes(extname(entry.name).toLowerCase()) && sourceExtensions.has(extname(entry.name).toLowerCase()) && directory !== root) ? [file] : [];
  });
}

function sha256(file) {
  return createHash('sha256').update(readFileSync(file)).digest('hex');
}

function csvRows(file) {
  const text = readFileSync(file, 'utf8').replace(bom, '');
  const rows = [];
  let row = [], field = '', quoted = false;
  for (let index = 0; index < text.length; index += 1) {
    const char = text[index];
    if (quoted) {
      if (char === '"' && text[index + 1] === '"') { field += '"'; index += 1; }
      else if (char === '"') quoted = false;
      else field += char;
    } else if (char === '"') quoted = true;
    else if (char === ',') { row.push(field); field = ''; }
    else if (char === '\n') { row.push(field.replace(/\r$/, '')); rows.push(row); row = []; field = ''; }
    else field += char;
  }
  if (field || row.length) { row.push(field.replace(/\r$/, '')); rows.push(row); }
  const [headers = [], ...values] = rows;
  return { headers, values: values.filter((value) => value.some((cell) => cell !== '')) };
}

function scalarType(values) {
  const present = values.filter((value) => value !== '');
  if (!present.length) return 'unknown';
  if (present.every((value) => /^(true|false)$/i.test(value))) return 'boolean';
  if (present.every((value) => /^-?\d+(\.\d+)?$/.test(value))) return 'number';
  if (present.every((value) => /^\d{4}-\d{2}-\d{2}T/.test(value))) return 'datetime';
  if (present.every((value) => /^\{[\s\S]*\}$|^\[[\s\S]*\]$/.test(value))) return 'json';
  return 'string';
}

function tableName(node) {
  const value = node.parameters?.dataTableId;
  if (typeof value === 'string') return value;
  if (value && typeof value === 'object') return value.cachedResultName ?? value.value ?? 'unresolved-table';
  return null;
}

const staticFixtures = new Set(['dt_synthetic_cases', 'dt_mock_utility_results', 'dt_decision_rules', 'dt_communication_templates', 'dt_business_register', 'dt_crm_accounts', 'dt_financial_records', 'dt_documents_index', 'dt_country_requirements', 'dt_process_catalog', 'dt_reason_codes']);
const tableMeaning = {
  dt_synthetic_cases: 'Static fixture: one row per synthetic case run (AUTH-001 … AUTH-010, AUTH-008-V1/V2) with the customer request.',
  dt_mock_utility_results: 'Static fixture: pre-computed utility outcome per Case_Run_ID + Check_Type (no submission_version); read by the seven utility workflows.',
  dt_decision_rules: 'Static fixture: governed decision matrix (rule id, priority, outcome, reason code, queue, template, rule status incl. TBD).',
  dt_communication_templates: 'Static fixture: customer/internal communication templates with {placeholders}.',
  dt_business_register: 'Static fixture (Business_Register): mock business registry.',
  dt_crm_accounts: 'Static fixture (CRM_Accounts): mock CRM/party records.',
  dt_financial_records: 'Static fixture (Financial_Records): mock credit/financial standing.',
  dt_documents_index: 'Static fixture (Documents_Index): synthetic documents per case.',
  dt_country_requirements: 'Static fixture: mandatory documents per country/process.',
  dt_process_catalog: 'Static fixture: process definition (P-1.1 NEW_LOA) and evidence permissions.',
  dt_reason_codes: 'Static fixture: reason-code vocabulary.',
  dt_utility_results_runtime: 'RUNTIME: one current result per case_run_id + submission_version + check_type written by the utility workflows and Workflow 95.',
  dt_cases_runtime: 'RUNTIME: current case state (status / current_stage / final_outcome / queue).',
  dt_decisions: 'RUNTIME: governed decision per case run written by Workflow 90 and updated by Workflow 91.',
  dt_evidence_requests: 'RUNTIME: customer evidence requests (lifecycle OPEN → RECEIVED → INSUFFICIENT/ACCEPTED/ESCALATED/CANCELLED).',
  dt_case_evidence: 'RUNTIME: evidence submitted against a request (text or uploaded PDF text and metadata).',
  dt_human_reviews: 'RUNTIME: human review queue and outcomes.',
  dt_communications: 'RUNTIME: communication drafts (never sent).',
  dt_audit_events: 'RUNTIME: append-only audit trail.',
};
const columnMeaning = {
  case_run_id: 'Case run identifier (one per submission version, e.g. AUTH-008-V2)', case_id: 'Logical case identifier shared by all versions', submission_version: 'Submission version of the case run',
  check_type: 'Mandatory check identifier (DOCUMENT_EXTRACTION … FINAL_VERIFICATION)', status: 'Outcome / lifecycle status', findings_json: 'Structured utility findings (JSON)', reason_codes: 'Semicolon-separated reason codes', rule_ids: 'Semicolon-separated decision-rule ids applied',
  rule_status_used: 'Status of the rule used (CONFIRMED_POC / ASSUMPTION / TBD)', evidence_references: 'Semicolon-separated evidence references', confidence: 'Confidence 0–1', human_review_required: 'Whether human review is required',
  superseded: 'Row replaced by a newer row (excluded from current results)', outcome: 'Governed outcome (APPROVE / REJECT / NEED_MORE_INFORMATION / MANUAL_REVIEW)', primary_reason_code: 'Primary governed reason code', target_queue: 'Operational queue', next_action: 'Next operational action',
  customer_safe_summary: 'Customer-safe explanation', communication_template_id: 'Template used for the draft communication', decision_json: 'Serialized decision package', evidence_request_id: 'Evidence request identifier', evidence_id: 'Evidence record identifier',
  review_id: 'Human review identifier', communication_id: 'Communication draft identifier', event_id: 'Audit event identifier', event_type: 'Audit event name', execution_id: 'n8n execution id (platform metadata)', created_at: 'Creation timestamp', updated_at: 'Last update timestamp',
  Rule_ID: 'Decision rule identifier', Priority: 'Rule priority (lower number applies first)', Final_Outcome: 'Outcome selected by the rule', Reason_Code: 'Reason code emitted by the rule', Rule_Status: 'CONFIRMED_POC | ASSUMPTION | TBD', Case_Run_ID: 'Case run identifier', Check_Type: 'Mandatory check identifier',
  Synthetic_Only: 'Marks synthetic data', Template_ID: 'Communication template identifier',
};

const files = sourceFiles();
const workflowFiles = files.filter((file) => extname(file) === '.json');
const csvFiles = files.filter((file) => extname(file) === '.csv');
const workflows = workflowFiles.map((file) => ({ file, json: JSON.parse(readFileSync(file, 'utf8')) }));
const tables = csvFiles.map((file) => ({ file, name: basename(file, '.csv'), ...csvRows(file) }));
const nodeRecords = workflows.flatMap(({ file, json }) => (json.nodes ?? []).map((node) => ({ file, workflow: json.name ?? basename(file), node })));
const isRead = (node) => ['get', 'getAll'].includes(node.parameters?.operation);
const users = (table) => nodeRecords.filter(({ node }) => tableName(node) === table.name);

// Upsert match keys as actually used by the workflows (the real de-facto keys of each runtime table).
const upsertKeys = new Map();
for (const { node } of nodeRecords) {
  const table = tableName(node);
  if (!table || node.parameters?.operation !== 'upsert') continue;
  const keys = (node.parameters?.filters?.conditions ?? []).map((condition) => condition.keyName).filter(Boolean);
  if (keys.length) upsertKeys.set(table, [...new Set([...(upsertKeys.get(table) ?? []), keys.join(' + ')])]);
}

mkdirSync(docsDir, { recursive: true });
mkdirSync(join(root, 'artifacts'), { recursive: true });

const inventory = [
  '# Source inventory', '',
  'Generated from the immutable root-level n8n JSON exports and CSV Data Table exports. No `source/`, `docs/`, or `samples/` directories were supplied: the artifacts sit in the repository root and are preserved in place, unchanged (verify with `npm run verify:sources`).', '',
  '## Preservation manifest', '',
  '| Path | Type | Bytes | SHA-256 |', '| --- | --- | ---: | --- |',
  ...files.map((file) => `| ${relative(root, file).replaceAll('\\', '/')} | ${extname(file).slice(1).toUpperCase()} | ${statSync(file).size} | \`${sha256(file)}\` |`),
  '', '## Workflow inventory', '',
  '| Source file | Workflow name | Nodes |', '| --- | --- | ---: |',
  ...workflows.map(({ file, json }) => `| ${basename(file)} | ${json.name ?? 'unnamed'} | ${(json.nodes ?? []).length} |`),
  '', '## Expected-workflow check', '',
  'Present: 03, 05, 06, 07A, 07B, 09, 10, 12, 90, 91, 92, 95, 96. **Absent: 93 – Case Status Portal.** Workflow 92 also calls `02 - SBO.02 - Profiling Super Agent`, which is not part of the upload (see docs/07). No workflow was invented for either.',
  '', '## Data-table inventory', '',
  '| Export | Rows | Columns | Classification |', '| --- | ---: | ---: | --- |',
  ...tables.map((table) => `| ${basename(table.file)} | ${table.values.length} | ${table.headers.length} | ${staticFixtures.has(table.name) ? 'Static reference fixture (seed)' : 'Runtime execution history — NOT seed data'} |`),
  '', '`dt_mock_utility_results` is keyed by `Case_Run_ID` + `Check_Type` and has no `submission_version`; `dt_utility_results_runtime` carries `case_run_id`, `submission_version` and `check_type`.',
  'The expected tables `Business_Register`, `CRM_Accounts`, `Financial_Records` and `Documents_Index` are exported as `dt_business_register`, `dt_crm_accounts`, `dt_financial_records` and `dt_documents_index`; `dt_country_requirements`, `dt_process_catalog` and `dt_reason_codes` are additional tables not in the expected list.',
].join('\n');

const edges = workflows.flatMap(({ file, json }) => Object.entries(json.connections ?? {}).flatMap(([from, groups]) => Object.values(groups ?? {}).flatMap((items) => (items ?? []).flatMap((item) => (item ?? []).map((edge) => ({ file, from, to: edge.node, type: edge.type ?? 'main' }))))));
const graph = [
  '# Workflow graph', '',
  '```mermaid', 'flowchart TD',
  ...workflows.map(({ file, json }) => `  ${createHash('sha1').update(file).digest('hex').slice(0, 8)}["${(json.name ?? basename(file)).replaceAll('"', "'")}"]`),
  ...nodeRecords.filter(({ node }) => /executeWorkflow|toolWorkflow/.test(node.type)).map(({ file, node }) => {
    const target = node.parameters?.workflowId?.cachedResultName ?? node.parameters?.workflowId?.value ?? node.name;
    return `  ${createHash('sha1').update(file).digest('hex').slice(0, 8)} -->|${node.name.replaceAll('"', "'")}| ${createHash('sha1').update(String(target)).digest('hex').slice(0, 8)}["${String(target).replaceAll('"', "'")}"]`;
  }),
  '```', '',
  '## Node-level edges', '', '| Workflow | From | To | Connection |', '| --- | --- | --- | --- |',
  ...edges.map((edge) => `| ${basename(edge.file)} | ${edge.from} | ${edge.to} | ${edge.type} |`), '',
  '## Table dependencies', '', '| Table | Readers | Writers |', '| --- | --- | --- |',
  ...tables.map((table) => {
    const uses = users(table);
    return `| ${table.name} | ${uses.filter(({ node }) => isRead(node)).map(({ workflow, node }) => `${workflow} / ${node.name}`).join('<br>') || '—'} | ${uses.filter(({ node }) => !isRead(node)).map(({ workflow, node }) => `${workflow} / ${node.name}`).join('<br>') || '—'} |`;
  }),
].join('\n');

const catalog = [
  '# n8n node catalog', '',
  'Every exported node is catalogued below. Parameter and code-node details are retained in `artifacts/source-node-catalog.json` to keep this review document readable. Target module / test / parity status for each node is in docs/05.', '',
  '| Workflow | Node ID | Node name | Node type | Table / dependency |', '| --- | --- | --- | --- | --- |',
  ...nodeRecords.map(({ file, node }) => `| ${basename(file)} | \`${node.id}\` | ${node.name} | \`${node.type}\` | ${tableName(node) ?? '—'} |`),
].join('\n');

const mismatchRows = [];
for (const { workflow, node } of nodeRecords) {
  const name = tableName(node);
  const table = tables.find((candidate) => candidate.name === name);
  if (!table) continue;
  const referenced = [...Object.keys(node.parameters?.columns?.value ?? {}), ...(node.parameters?.filters?.conditions ?? []).map((condition) => condition.keyName)].filter(Boolean);
  for (const column of new Set(referenced)) {
    if (table.headers.includes(column)) continue;
    const near = table.headers.find((header) => header.toLowerCase() === column.toLowerCase());
    mismatchRows.push(`| ${name} | ${column} | ${workflow} / ${node.name} | ${near ? `case-only difference from export column \`${near}\`` : 'column absent from the export'} |`);
  }
}

const dictionary = [
  '# Data dictionary', '',
  'Types are inferred only from the supplied CSV values; empty-only columns are `unknown`. No column was invented. Source column names and casing are preserved exactly in the raw import tables (`source.*` for static fixtures, `history.*` for exported runtime rows). The target database type applies to the typed domain adapter / runtime tables.', '',
  'Key columns are taken from the **upsert filters the workflows actually use**, not guessed from column names. Runtime tables in the target are keyed as documented in `packages/persistence/migrations`.', '',
  ...tables.flatMap((table) => {
    const uses = users(table);
    const readers = uses.filter(({ node }) => isRead(node)).map(({ workflow, node }) => `${workflow} / ${node.name}`);
    const writers = uses.filter(({ node }) => !isRead(node)).map(({ workflow, node }) => `${workflow} / ${node.name}`);
    const keys = upsertKeys.get(table.name) ?? [];
    const keyColumns = new Set(keys.flatMap((key) => key.split(' + ').map((column) => column.toLowerCase())));
    return [
      `## ${table.name}`, '', `Source: \`${basename(table.file)}\`; ${table.values.length} exported rows. **${staticFixtures.has(table.name) ? 'Static reference fixture' : 'Runtime execution history (not seed data)'}.** ${tableMeaning[table.name] ?? ''}`, '',
      keys.length ? `Upsert match key(s) used by the workflows: ${keys.map((key) => `\`${key}\``).join('; ')}.` : 'No workflow upserts into this table.', '',
      '| Original column | Source type | Target type | Nullable / default | Key | Readers | Writers | Domain meaning |', '| --- | --- | --- | --- | --- | --- | --- | --- |',
      ...table.headers.map((header, index) => {
        const values = table.values.map((row) => row[index] ?? '');
        const nullable = values.some((value) => value === '') ? 'nullable (blank in export)' : 'not null in export';
        const type = scalarType(values);
        const key = keyColumns.has(header.toLowerCase()) ? `upsert key (${keys.join('; ')})` : '—';
        return `| ${header} | ${type} | ${type === 'datetime' ? 'timestamp with time zone' : type === 'json' ? 'jsonb' : type === 'number' ? 'numeric' : type === 'boolean' ? 'boolean' : 'text'} | ${nullable} | ${key} | ${readers.join('<br>') || '—'} | ${writers.join('<br>') || '—'} | ${columnMeaning[header] ?? columnMeaning[header.toLowerCase()] ?? `Field of ${table.name}`} |`;
      }), '',
    ];
  }),
  '## Columns referenced by workflow table mappings but not present in the export as written', '',
  'Recorded, not "fixed": the workflows are the source of truth for what they write; the exports are snapshots.', '',
  '| Table | Referenced column | Workflow / node | Finding |', '| --- | --- | --- | --- |',
  ...(mismatchRows.length ? [...new Set(mismatchRows)] : ['| — | — | — | none |']),
].join('\n');

writeFileSync(join(docsDir, '01-source-inventory.md'), inventory);
writeFileSync(join(docsDir, '02-workflow-graph.md'), graph);
writeFileSync(join(docsDir, '03-node-catalog.md'), catalog);
writeFileSync(join(docsDir, '04-data-dictionary.md'), dictionary);
writeFileSync(join(root, 'artifacts', 'source-node-catalog.json'), JSON.stringify(nodeRecords.map(({ file, workflow, node }) => ({ sourceFile: basename(file), workflow, id: node.id, name: node.name, type: node.type, parameters: node.parameters, connections: node.connections })), null, 2));
writeFileSync(join(root, 'artifacts', 'source-checksums.json'), JSON.stringify(files.map((file) => ({ path: relative(root, file).replaceAll('\\', '/'), bytes: statSync(file).size, sha256: sha256(file) })), null, 2));

console.log(`Analysed ${workflows.length} workflow exports, ${tables.length} CSV exports, and ${nodeRecords.length} n8n nodes.`);
