/**
 * Builds docs/05-n8n-to-code-traceability.md and artifacts/traceability.json from the source node catalogue and scripts/traceability-map.ts.
 * Fails (exit 1) when: a node has no mapping; a mapping matches nothing; a referenced test file/title does not exist; a non-UNSUPPORTED
 * node has no test.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import rules, { type ParityStatus, type Rule } from './traceability-map.js';

interface CatalogNode { id: string; name: string; type: string; sourceFile: string; workflow: string; parameters: Record<string, unknown>; }
const catalog = JSON.parse(readFileSync('artifacts/source-node-catalog.json', 'utf8')) as CatalogNode[];
const workflowKey = (file: string): string => file.split(' ')[0]!;

function matches(rule: Rule, node: CatalogNode): boolean {
  if (workflowKey(node.sourceFile) !== rule.workflow) return false;
  return Array.isArray(rule.nodes) ? rule.nodes.includes(node.name) : rule.nodes.test(node.name);
}

const errors: string[] = [];
const testCache = new Map<string, string>();
function testText(file: string): string | undefined {
  if (!testCache.has(file)) testCache.set(file, existsSync(file) ? readFileSync(file, 'utf8') : '');
  return testCache.get(file) || undefined;
}

const rows = catalog.map((node) => {
  const rule = rules.find((candidate) => matches(candidate, node));
  if (!rule) { errors.push(`UNMAPPED NODE: ${node.sourceFile} / ${node.name} [${node.type}] (${node.id})`); return undefined; }
  if (rule.status !== 'UNSUPPORTED' && rule.tests.length === 0) errors.push(`NO TEST: ${node.sourceFile} / ${node.name}`);
  for (const [file, title] of rule.tests) {
    const text = testText(file);
    if (text === undefined) errors.push(`MISSING TEST FILE ${file} (node ${node.name})`);
    else if (!text.includes(title)) errors.push(`MISSING TEST TITLE "${title}" in ${file} (node ${node.name})`);
  }
  const table = node.type.endsWith('dataTable') ? String((node.parameters as { dataTableId?: { cachedResultName?: string } }).dataTableId?.cachedResultName ?? '') : '';
  const operation = node.type.endsWith('dataTable') ? String((node.parameters as { operation?: string }).operation ?? '') : '';
  const dependency = table ? `${table} (${operation || 'insert'})` : node.type.includes('langchain') ? 'LLM / agent runtime' : node.type.endsWith('executeWorkflow') ? 'sub-workflow call' : '—';
  return { workflowFile: node.sourceFile, workflowName: node.workflow, nodeId: node.id, nodeName: node.name, nodeType: node.type, inputOutputContract: rule.io, dependency, targetModule: rule.module, targetTests: rule.tests.map(([file, title]) => `${file} › ${title}`), parityStatus: rule.status as ParityStatus, notes: rule.notes ?? '' };
}).filter((row): row is NonNullable<typeof row> => Boolean(row));

for (const rule of rules) if (!catalog.some((node) => matches(rule, node))) errors.push(`RULE MATCHES NOTHING: ${rule.workflow} ${Array.isArray(rule.nodes) ? rule.nodes.join(' | ') : String(rule.nodes)}`);
const seen = new Set<string>();
for (const node of catalog) { const key = `${node.sourceFile}|${node.id}`; if (seen.has(key)) errors.push(`DUPLICATE NODE ${key}`); seen.add(key); }

if (errors.length > 0) { console.error(errors.join('\n')); console.error(`\n${errors.length} traceability error(s).`); process.exit(1); }

const counts: Record<string, number> = {};
for (const row of rows) counts[row.parityStatus] = (counts[row.parityStatus] ?? 0) + 1;
writeFileSync('artifacts/traceability.json', JSON.stringify({ generatedFrom: 'artifacts/source-node-catalog.json + scripts/traceability-map.ts', totalNodes: rows.length, statusCounts: counts, rows }, null, 2));

const escape = (value: string): string => value.replaceAll('|', '\\|').replaceAll('\n', ' ');
const header = `# n8n-to-code traceability matrix

Generated by \`npm run docs:traceability\` from \`artifacts/source-node-catalog.json\` (all ${rows.length} nodes of the 13 uploaded workflows) and \`scripts/traceability-map.ts\`.
The generator fails if any node is unmapped, any mapping matches nothing, or any referenced test title does not exist in its test file, so no node can be silently omitted.

## Parity status legend

| Status | Meaning |
| --- | --- |
| PARITY_TESTED | Behaviour implemented in code and covered by an automated test. |
| PARITY_TESTED_DEVIATION | Implemented and tested, with a documented deliberate deviation (see Notes and docs/07). |
| REPLACED_BY_PLATFORM | n8n plumbing (trigger, sub-workflow call, form / chat rendering) replaced by an API route or UI; covered by API / browser tests. |
| SOURCE_DEFECT_NOT_REPRODUCED | The source behaviour is a defect; the documented intent is implemented and tested instead. |
| UNSUPPORTED | Explicitly out of scope (n8n editor scaffolding); the reason is in Notes. |

## Summary

| Status | Nodes |
| --- | ---: |
${Object.entries(counts).map(([status, count]) => `| ${status} | ${count} |`).join('\n')}
| **Total** | **${rows.length}** |

## Matrix

| Workflow file | Workflow name | Node ID | Node name | Node type | Input / output contract | Table / API dependency | Target code module | Target test | Parity status | Notes |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
`;
const body = rows.map((row) => `| ${escape(row.workflowFile)} | ${escape(row.workflowName)} | ${row.nodeId} | ${escape(row.nodeName)} | ${escape(row.nodeType)} | ${escape(row.inputOutputContract)} | ${escape(row.dependency)} | ${escape(row.targetModule)} | ${escape(row.targetTests.join('; ') || '—')} | ${row.parityStatus} | ${escape(row.notes)} |`).join('\n');
writeFileSync('docs/05-n8n-to-code-traceability.md', `${header}${body}\n`);
console.log(`Traceability OK: ${rows.length} nodes mapped. ${JSON.stringify(counts)}`);
