/**
 * Builds docs/05-to-be-process-conformance.md and artifacts/conformance.json from scripts/process-map.ts.
 * Fails (exit 1) when a referenced test file or test title does not exist, or when an in-scope step has no test.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { steps, type StepStatus } from './process-map.js';

const errors: string[] = [];
const cache = new Map<string, string>();
const text = (file: string): string | undefined => { if (!cache.has(file)) cache.set(file, existsSync(file) ? readFileSync(file, 'utf8') : ''); return cache.get(file) || undefined; };
const ids = new Set<string>();
for (const step of steps) {
  if (ids.has(step.id)) errors.push(`DUPLICATE STEP ${step.id}`);
  ids.add(step.id);
  if (step.status !== 'OUT_OF_SCOPE' && step.tests.length === 0) errors.push(`NO TEST: ${step.id} ${step.step}`);
  for (const [file, title] of step.tests) {
    const content = text(file);
    if (content === undefined) errors.push(`MISSING TEST FILE ${file} (step ${step.id})`);
    else if (!content.includes(title)) errors.push(`MISSING TEST TITLE "${title}" in ${file} (step ${step.id})`);
  }
}
if (errors.length > 0) { console.error(errors.join('\n')); console.error(`\n${errors.length} conformance error(s).`); process.exit(1); }

const counts: Record<StepStatus, number> = { IMPLEMENTED: 0, SIMULATED: 0, PLATFORM: 0, TARGET_ADDITION: 0, OUT_OF_SCOPE: 0 };
for (const step of steps) counts[step.status] += 1;
mkdirSync('artifacts', { recursive: true });
writeFileSync('artifacts/conformance.json', JSON.stringify({ source: 'E&SMB-BO To-Be Process, profiling, pages 12-13 (photographed), plus product-owner requests', totalSteps: steps.length, statusCounts: counts, steps }, null, 2));

const escape = (value: string): string => value.replaceAll('|', '\\|').replaceAll('\n', ' ');
const md = `# To-Be process conformance

Generated by \`npm run docs:conformance\` from \`scripts/process-map.ts\`. The source of truth for behaviour is the **E&SMB-BO To-Be process diagrams** (profiling, "New LOA Processing - triggered by customer through conversational chatbot", pages 12-13), read from photographs. The earlier n8n export is archived (docs/09).
The generator fails if a referenced test file or title does not exist, so no step can claim a test that is not there.

| Status | Meaning |
| --- | --- |
| IMPLEMENTED | Behaviour implemented and tested. |
| SIMULATED | Implemented against a **synthetic stand-in** for an external system (DUL API, government portal / UAE Pass, BCRM, AVCV). |
| PLATFORM | A diagram element that is plumbing here (portal login, ticket creation) and is replaced by the app. |
| TARGET_ADDITION | Requested by the product owner; not drawn in the diagrams. |
| OUT_OF_SCOPE | In the diagrams but not built yet. |

## Summary

| Status | Steps |
| --- | ---: |
${Object.entries(counts).map(([status, count]) => `| ${status} | ${count} |`).join('\n')}
| **Total** | **${steps.length}** |

## Steps

| ID | Lane | Diagram step | Code | Tests | Status | Notes |
| --- | --- | --- | --- | --- | --- | --- |
${steps.map((step) => `| ${step.id} | ${escape(step.lane)} | ${escape(step.step)} | ${escape(step.module)} | ${escape(step.tests.map(([file, title]) => `${file} › ${title}`).join('; ') || '—')} | ${step.status} | ${escape(step.note ?? '')} |`).join('\n')}
`;
writeFileSync('docs/05-to-be-process-conformance.md', md);
console.log(`Conformance OK: ${steps.length} steps mapped. ${JSON.stringify(counts)}`);
