/**
 * The To-Be process conformance map (docs/09). Each step of "New LOA Processing - triggered by customer through conversational chatbot"
 * (E&SMB-BO To-Be Process, profiling, p.12-13) is mapped to the code that implements it and the tests that prove it.
 * `npm run docs:conformance` fails when a referenced test file or test title does not exist.
 *
 * Status:
 *   IMPLEMENTED     - behaviour implemented and tested
 *   SIMULATED       - implemented against a synthetic stand-in for an external system (DUL API, government portal / UAE Pass, BCRM, AVCV service)
 *   PLATFORM        - a diagram element that is plumbing here (ticket creation in BCRM, portal login) and is replaced by the app
 *   TARGET_ADDITION - requested by the product owner, not drawn in the diagrams
 *   OUT_OF_SCOPE    - present in the diagrams but not built yet (listed honestly in docs/09)
 */
export type StepStatus = 'IMPLEMENTED' | 'SIMULATED' | 'PLATFORM' | 'TARGET_ADDITION' | 'OUT_OF_SCOPE';
export type TestRef = [file: string, title: string];
export interface ProcessStep { id: string; lane: string; step: string; module: string; tests: TestRef[]; status: StepStatus; note?: string; }

const LOA: (title: string) => TestRef = (title) => ['tests/loa-process.test.ts', title];
const GOV: (title: string) => TestRef = (title) => ['tests/governance.test.ts', title];
const API: (title: string) => TestRef = (title) => ['tests/api.test.ts', title];
const SEC: (title: string) => TestRef = (title) => ['tests/security.test.ts', title];
const PER: (title: string) => TestRef = (title) => ['tests/persistence.test.ts', title];
const AGT: (title: string) => TestRef = (title) => ['tests/agent-runtime.test.ts', title];
const ATT: (title: string) => TestRef = (title) => ['tests/chat-attachments.test.ts', title];
const SQL: (title: string) => TestRef = (title) => ['tests/sql.integration.test.ts', title];
const E2E: (title: string) => TestRef = (title) => ['tests/e2e/portal.spec.ts', title];

export const steps: ProcessStep[] = [
  // ------------------------------------------------------------------ Customer lane
  { id: 'C1', lane: 'B2B Customer', step: 'Customer logs in and places a request with the conversational chatbot', module: 'apps/web/src/pages/ChatPage.tsx · apps/api/src/app.ts (POST /api/chat)', tests: [E2E('a new customer starts with a name and a company'), API('a new customer introduces themselves, attaches the documents')], status: 'PLATFORM', note: 'The B2B portal login is not modelled; the chat is the portal. Sessions are cookie-based and synthetic.' },
  { id: 'C2', lane: 'B2B Customer', step: 'Chatbot analyses the customer intent and asks for the required valid information', module: 'packages/workflows/src/chat.ts#handleChatMessage · intake.ts#extractIntake', tests: [LOA('greets a new customer and asks for a name and a company')], status: 'IMPLEMENTED', note: 'Intent is fixed to New LOA (deterministic name/company extraction, no model); other intents in the diagrams are out of scope.' },
  { id: 'C3', lane: 'B2B Customer', step: 'Customer needs further guidance? Customer provides the chatbot with the details', module: 'packages/workflows/src/chat.ts (INTAKE state)', tests: [LOA('asks only for what is missing, over several turns')], status: 'IMPLEMENTED' },
  { id: 'C4', lane: 'B2B Customer', step: 'Chatbot connects the customer with a human agent; the human agent creates the ticket', module: 'packages/workflows/src/chat.ts (NEW_LEAD) · intake.ts#openIntakeCase', tests: [LOA('a company that is NOT on record becomes a new lead'), E2E('a company that is not on record is confirmed first and becomes a new lead with onboarding pending')], status: 'SIMULATED', note: 'A company that is not on record gets a new-lead case and a specialist follow-up; nothing is verified or approved. There is no live human hand-over.' },
  // ------------------------------------------------------------------ SBO.01 orchestrator
  { id: 'O1', lane: 'SBO.01 Orchestrator', step: 'Converts the request into a ticket and creates it in BCRM', module: 'packages/workflows/src/intake.ts#openIntakeCase · persistence createIntakeCase', tests: [LOA('a company on record: opens a case and asks for the Emirates ID'), SQL('intake cases: sequential ids')], status: 'PLATFORM', note: 'BCRM is replaced by the case store (AUTH-101, AUTH-102, ...).' },
  { id: 'O2', lane: 'SBO.01 Orchestrator', step: 'Validates the request and asks for / collects the documents (Emirates ID, Trade License, Establishment Card)', module: 'packages/workflows/src/chat.ts · evidence.ts#submitDocumentEvidence / resolveEvidence', tests: [LOA('missing documents are named and the same request stays open'), LOA('after three attempts that still miss documents'), ATT('documents in different formats (a Word file and two PDFs)')], status: 'IMPLEMENTED', note: 'Documents are the only evidence (PDF, Word, images); typed text is refused.' },
  { id: 'O3', lane: 'SBO.01 Orchestrator', step: 'Triggers SBO.02 for New LOA Processing', module: 'packages/workflows/src/evidence.ts#resolveEvidenceAndContinue → super-agent.ts#resumeAssessment', tests: [LOA('Fatima (licence owner, valid documents): all five checks pass in order')], status: 'IMPLEMENTED' },
  { id: 'O4', lane: 'SBO.01 Orchestrator', step: 'Documents not uploaded / discrepancies: SBO.11 drafts an email for the pending information', module: 'packages/workflows/src/super-agent.ts#classifyContinuation · governance COMM-NEED-INFO', tests: [LOA('Omar (not the licence owner): a POA is requested'), GOV('derives missing information, conflicts and a customer-safe summary')], status: 'IMPLEMENTED', note: 'The request is made in the chat itself; the drafted email is a draft only.' },
  { id: 'O5', lane: 'SBO.01 Orchestrator', step: 'Could not classify: route the request to the exception queue for manual review', module: 'packages/workflows/src/super-agent.ts#createReviewForDecision · human-review.ts#listReviewDashboard', tests: [LOA('a known company but a person that is not in the identity register'), LOA('lists every review with its case')], status: 'IMPLEMENTED' },
  // ------------------------------------------------------------------ SBO.02 + utility agents
  { id: 'S1', lane: 'SBO.02 Super Agent', step: 'Triggers SBO.06 (Trade License Check agent) to perform the TL and EC checks', module: 'packages/domain/src/loa.ts#tradeLicenseCheck · workflows/src/utilities.ts', tests: [PER('exposes exactly the five specialist tools'), AGT('exposes exactly the five specialist tools')], status: 'IMPLEMENTED' },
  { id: 'S2', lane: 'SBO.06 Trade License agent', step: 'Extracts the EC and TL fields; matches the Establishment Card and Trade License name', module: 'packages/domain/src/loa.ts#classifyDocument / extractFields', tests: [ATT('is read and recognised'), LOA('reads fields even when a PDF or OCR puts the whole document on one line')], status: 'IMPLEMENTED' },
  { id: 'S3', lane: 'SBO.06 Trade License agent', step: 'Trade License not readable: perform the QR check', module: 'packages/domain/src/loa.ts#resolveLicense', tests: [LOA('Mariam: the licence number is unreadable, so the QR code is used'), LOA('a licence with neither a readable number nor a QR code asks the customer')], status: 'IMPLEMENTED' },
  { id: 'S4', lane: 'SBO.06 Trade License agent', step: 'Uses the DUL API to verify the TL details and structures the output', module: 'packages/domain/src/loa.ts (tradeLicenseRegister, dulApiAvailable)', tests: [LOA('Fatima (licence owner, valid documents): all five checks pass in order')], status: 'SIMULATED', note: 'The DUL API is a synthetic register.' },
  { id: 'S5', lane: 'SBO.06 Trade License agent', step: 'DUL API failure: log in to the government portal with UAE Pass and validate the TL', module: 'packages/domain/src/loa.ts#tradeLicenseCheck (GOVERNMENT_PORTAL_UAE_PASS)', tests: [LOA('Noura: the DUL API is down'), E2E('Noura: the DUL API is down')], status: 'SIMULATED', note: 'No portal or UAE Pass call is made; the fallback path is modelled and reported as PASS_WITH_FLAG.' },
  { id: 'S6', lane: 'SBO.02 Super Agent', step: 'Collects the output and decides the next step (stops at a terminal result)', module: 'packages/workflows/src/super-agent.ts#createToolbox · governance determineDecision', tests: [PER('stops after a terminal result: later tools are refused'), GOV('an explicit terminal business rule takes precedence'), AGT('an LLM that forces APPROVE on an expired licence is overridden')], status: 'IMPLEMENTED' },
  { id: 'S7', lane: 'SBO.02 Super Agent', step: 'TL expired: reject the request, SBO.11 emails the customer, SBO.20 RCA agent analyses the reason', module: 'packages/domain/src/loa.ts (TL-002) · super-agent.ts#requestRootCauseAnalysis', tests: [LOA('%s → REJECT %s: stops at the failing check'), E2E('a rejection is recommended')], status: 'IMPLEMENTED', note: 'Every rejection waits for a human to confirm it on the review dashboard; the email is a draft and the RCA is a deterministic summary.' },
  { id: 'S8', lane: 'SBO.02 Super Agent', step: 'Name does not match: reject the request (SBO.11 + SBO.20)', module: 'packages/domain/src/loa.ts (TL-004, ID-001)', tests: [LOA('the Emirates ID name must match the name in the request'), LOA('%s → REJECT %s: stops at the failing check')], status: 'IMPLEMENTED' },
  { id: 'S9', lane: 'SBO.02 Super Agent', step: 'Triggers SBO.07 for identity validation', module: 'packages/domain/src/loa.ts#identityValidation', tests: [LOA('an expired Emirates ID is a fixable gap')], status: 'IMPLEMENTED' },
  { id: 'S10', lane: 'SBO.07 Identity agent', step: 'Cross-checks the EID and EC with the TL name and returns a structured output', module: 'packages/domain/src/loa.ts#identityValidation (recordedPerson)', tests: [LOA('Fatima (licence owner, valid documents): all five checks pass in order'), LOA('a known company but a person that is not in the identity register')], status: 'SIMULATED', note: 'The identity register is synthetic.' },
  { id: 'S11', lane: 'SBO.02 Super Agent', step: 'EID, EC and TL name mismatch observed: reject', module: 'packages/domain/src/loa.ts (ID-001)', tests: [LOA('%s → REJECT %s: stops at the failing check')], status: 'IMPLEMENTED' },
  { id: 'S12', lane: 'SBO.02 Super Agent', step: 'Triggers the POA/MOA workflow: document available? checks cleared / not cleared', module: 'packages/domain/src/loa.ts#poaMoaCheck', tests: [LOA('Omar (not the licence owner): a POA is requested'), LOA('Hessa: acts under an expired POA')], status: 'IMPLEMENTED' },
  { id: 'S12a', lane: 'SBO.02 Super Agent', step: 'Who is authorised without a POA/MOA (product owner rule): ID verified; recorded as owner, manager with representative authority or authorised signatory in the approved source; capacity covers the requested action; licence current and consistent; no conflicting evidence or limitation', module: 'packages/domain/src/loa.ts#poaMoaCheck (RecordedPerson, POA-004)', tests: [LOA('a manager recorded with full representative authority needs no POA'), LOA('a manager whose recorded capacity does not cover every requested action still needs a POA'), LOA('a person on the establishment card without a recorded authority'), LOA('a recorded limitation or conflicting evidence on the person')], status: 'IMPLEMENTED', note: 'Broader than owner-only, narrower than anyone listed on the Establishment Card.' },
  { id: 'S13', lane: 'SBO.02 / SBO.09 / SBO.08', step: 'Triggers SBO.09 for the bad-debt and blue-collar checks; SBO.08 cross-checks duplicate PDs in BCRM', module: 'packages/domain/src/loa.ts#badDebtCheck', tests: [LOA('Layla: the bad-debt check sees the duplicate party IDs')], status: 'SIMULATED', note: 'BCRM is a synthetic party register.' },
  { id: 'S14', lane: 'SBO.02 / SBO.10', step: 'No bad debt or blue-collar behaviour: SBO.02 triggers SBO.10 to run the AVCV (Address Verification and Credit Verification) workflow', module: 'packages/domain/src/loa.ts#avcvVerification (address + credit outcomes)', tests: [LOA('Fatima (licence owner, valid documents): all five checks pass in order')], status: 'SIMULATED', note: 'AVCV is a synthetic register with one outcome for the address and one for the credit profile (positive, negative, discrepancy, unable to verify, refer, insufficient information); no field visit or bureau lookup happens.' },
  { id: 'S14a', lane: 'SBO.10 AVCV', step: 'AVCV outcomes: only an adverse result is a rejection; a discrepancy, unable-to-verify or refer goes to a specialist; insufficient information asks for proof of address', module: 'packages/domain/src/loa.ts (AV-001..004)', tests: [LOA('%s → MANUAL_REVIEW %s (%s)'), LOA('insufficient information for the address verification asks for proof of address'), LOA('a proof of address held by someone else does not satisfy the verification')], status: 'SIMULATED' },
  { id: 'S15', lane: 'SBO.02 Super Agent', step: 'AVCV successful: approve the request and SBO.11 shares the communication with the stakeholders', module: 'packages/governance/src/index.ts (FINAL-001, COMM-APPROVE)', tests: [GOV('approves only when every mandatory check passes (FINAL-001)'), SQL('Fatima approves: five unique rows')], status: 'IMPLEMENTED', note: 'The communication is a draft; nothing is sent and nothing is written to a production system.' },
  { id: 'S16', lane: 'SBO.02 Super Agent', step: 'AVCV adverse: reject the request (SBO.11 + SBO.20)', module: 'packages/domain/src/loa.ts (AV-001)', tests: [LOA('%s → REJECT %s: stops at the failing check')], status: 'IMPLEMENTED' },
  { id: 'S17', lane: 'SBO.02 Super Agent', step: 'A lookup that is unavailable or unmatched is never treated as proof of invalidity: a specialist decides', module: 'packages/domain/src/loa.ts (TL-005, ID-003, POA-003, AV-002)', tests: [LOA('a known company but a person that is not in the identity register')], status: 'IMPLEMENTED' },
  // ------------------------------------------------------------------ Governance (kept from the migration)
  { id: 'G1', lane: 'Governance', step: 'The deterministic finalizer, not the model, issues every final outcome; the model only recommends', module: 'packages/governance/src/index.ts (no model dependency)', tests: [GOV('is deterministic and contains no model dependency'), AGT('an LLM that stops early and recommends APPROVE cannot override deterministic governance')], status: 'IMPLEMENTED' },
  { id: 'G2', lane: 'Governance', step: 'Runtime results are unique per case_run_id + submission_version + check_type', module: 'packages/persistence (runtime_utility_results)', tests: [LOA('the persisted result key is the three-part case_run_id + submission_version + check_type'), PER('rerunning the same utility is idempotent')], status: 'IMPLEMENTED' },
  { id: 'G3', lane: 'Governance', step: 'Customer documents are data, never instructions', module: 'packages/domain/src/loa.ts#classifyDocument (regex reader, no model)', tests: [SEC('instructions written inside a document change nothing'), LOA('a file that is none of the four supported document types')], status: 'IMPLEMENTED' },
  // ------------------------------------------------------------------ Requested by the product owner
  { id: 'T1', lane: 'Product owner request', step: 'Evidence is documents only: typed text is never accepted as evidence', module: 'packages/workflows/src/chat.ts · evidence.ts · apps/api (no text route)', tests: [LOA('typed text is not evidence'), SEC('typed text can never become evidence, by any route'), E2E('documents only: while a document request is open there is no text box')], status: 'TARGET_ADDITION' },
  { id: 'T2', lane: 'Product owner request', step: 'Documents are attached in the same chat window (PDF, Word, images); a missing or replaced document is requested again in the same window', module: 'apps/web/src/pages/ChatPage.tsx · POST /api/chat/evidence', tests: [E2E('Omar is not the licence owner'), ATT('re-upload is always possible'), API('a POA is requested in the same conversation')], status: 'TARGET_ADDITION' },
  { id: 'T3', lane: 'Product owner request', step: 'Review dashboard: every review with its Review ID, status, checks, documents and root-cause analysis', module: 'apps/web/src/pages/ReviewPage.tsx · GET /api/reviews[/:id]', tests: [API('lists every review on the dashboard'), E2E('the dashboard lists the review with its Review ID')], status: 'TARGET_ADDITION' },
  { id: 'T4', lane: 'Product owner request', step: 'Reopen a rejected or incomplete request from the review dashboard; the customer answers in the chat (replaces the resubmission page)', module: 'packages/workflows/src/reopen.ts · POST /api/cases/:id/reopen', tests: [LOA('a reviewer reopens a rejected case'), API('reopening a rejected case creates a new version'), SQL('reopen works on real SQL'), E2E('reopen: the reviewer reopens a rejected case')], status: 'TARGET_ADDITION' },
  { id: 'T5', lane: 'Product owner request', step: 'A company that is not on record is only a new lead: never approved', module: 'packages/workflows/src/intake.ts#openIntakeCase', tests: [LOA('a company that is NOT on record becomes a new lead'), API('a company that is not on record becomes a new lead over HTTP')], status: 'TARGET_ADDITION' },
  { id: 'T6', lane: 'Product owner request', step: 'The agent may recommend a rejection, but a rejection is never final or communicated externally without human confirmation', module: 'packages/workflows/src/chat-response.ts · apps/api/src/app.ts#publicReply', tests: [API('a recommended rejection is never shown to the customer'), LOA('drafts the email (SBO.11), requests root-cause analysis (SBO.20) and waits for a human'), E2E('a rejection is recommended')], status: 'TARGET_ADDITION', note: 'The customer sees "awaiting specialist confirmation"; the reason and the decision are visible only on the review dashboard.' },  { id: 'T7', lane: 'Product owner request', step: 'Customer-facing request catalog: eight intent categories and every request type of the operating model (profiling, verifier task, processing), with a stage owner for each', module: 'packages/domain/src/catalog.ts · GET /api/catalog', tests: [['tests/catalog.test.ts', 'offers the eight customer-facing categories'], ['tests/catalog.test.ts', 'assigns request types to the stage that owns them'], E2E('the assistant offers eight topics')], status: 'TARGET_ADDITION' },
  { id: 'T8', lane: 'Product owner request', step: 'Pre-populated standard queries and free-text intent recognition start a request in one step', module: 'packages/domain/src/catalog.ts#matchRequestType · workflows/src/chat.ts', tests: [['tests/catalog.test.ts', 'recognises "%s" as %s'], E2E('pre-populated standard queries start a request in one click'), E2E('typing a request in your own words is recognised')], status: 'TARGET_ADDITION' },
  { id: 'T9', lane: 'Product owner request', step: 'Requests that are not automated are captured and routed to the stage that owns them (profiling, verifier task, processing) — never checked, approved or changed', module: 'packages/workflows/src/capture.ts · operations.ts · GET /api/operations', tests: [['tests/catalog.test.ts', 'a chosen request that is not automated is captured and routed'], ['tests/catalog.test.ts', 'the operations overview counts captured requests per stage'], E2E('the Operations page shows the six stages')], status: 'TARGET_ADDITION', note: 'Only New LOA is automated. Control tower, governance and reporting are shown for the operating model only.' },  // ------------------------------------------------------------------ Not built
  { id: 'T10', lane: 'Product owner request', step: 'A name that is not a full name is asked for again (first and last name) before anything is created', module: 'packages/workflows/src/chat.ts#handleChatMessage', tests: [LOA('a name that is not a full name is asked for again before anything is created')], status: 'TARGET_ADDITION' },
  { id: 'T11', lane: 'Product owner request', step: 'A company that is not on record is confirmed with the customer before the lead is created; a confirmed lead is recorded with onboarding status PENDING and the customer is told a representative will get back', module: 'packages/workflows/src/chat.ts#proceed · capture.ts#captureNewLead', tests: [LOA('a company that is not on record is confirmed with the customer first; a correction continues the normal flow'), LOA('a confirmed lead is recorded with onboarding status PENDING, tells the customer a representative will get back, and never checks or approves'), E2E('a company that is not on record is confirmed first and becomes a new lead with onboarding pending')], status: 'TARGET_ADDITION' },
  { id: 'T12', lane: 'Product owner request', step: 'A human can reopen a closed case; a closed, human-confirmed rejection is reopened by the customer only once they furnish documents', module: 'packages/workflows/src/reopen.ts · chat.ts#findClosedRejection', tests: [LOA('a human can reopen a closed (completed) rejected review from the dashboard'), LOA('a closed, human-confirmed rejection is reopened by the customer only once they furnish documents; before confirmation nothing is offered')], status: 'TARGET_ADDITION' },
  { id: 'T13', lane: 'Product owner request', step: 'The Operations page shows the operating-model stages as a stepper with the New LOA pipeline, new leads, captured requests and recent activity', module: 'apps/web/src/pages/OperationsPage.tsx · packages/workflows/src/operations.ts', tests: [E2E('the Operations page shows the six stages of the operating model with only profiling live')], status: 'TARGET_ADDITION' },
  { id: 'X1', lane: 'Not built', step: 'Other To-Be processes: Mobile Re-Registration, Document Update, Combo (Document Update + LOA / LOA + Re-Registration), Regularization, PMP, TASK/TKT, Data Quality Assurance', module: '-', tests: [], status: 'OUT_OF_SCOPE', note: 'Only the New LOA chatbot-triggered process was built. The other diagrams reuse SBO.05 (document extraction), SBO.12 (system data check / reconciliation) and other utility agents that are not implemented.' },
  { id: 'X3', lane: 'Not built', step: 'Automation of the verifier task (MNP, activations, transfer of ownership, SIM replacement, AVCV field work, legal letters, biometric verification), processing (order creation, quality checks, contract validation, delivery, lifecycle tracking), the control tower, governance and reporting', module: '-', tests: [], status: 'OUT_OF_SCOPE', note: 'Requests for these are captured and routed (T9); nothing runs on them.' },
  { id: 'X2', lane: 'Not built', step: 'Ticket-triggered and channel-partner-triggered variants of New LOA; SBO.05 document extraction agent; SBO.13 order execution; SBO.14 case lifecycle tracking', module: '-', tests: [], status: 'OUT_OF_SCOPE', note: 'The chat variant is the only entry point. The ticket variants share the same five checks and could be added on top.' },
];
