/**
 * Single source of truth mapping every n8n node to its target module and test.
 * scripts/build-traceability.ts resolves all 229 catalogued nodes against these rules and FAILS when a node is unmapped or when a referenced
 * test title cannot be found in the referenced test file, so no node can be silently omitted.
 */
export type ParityStatus =
  | 'PARITY_TESTED'                // behaviour implemented and covered by an automated test
  | 'PARITY_TESTED_DEVIATION'      // implemented and tested, with a documented, deliberate deviation (see notes / docs/07)
  | 'REPLACED_BY_PLATFORM'         // n8n plumbing (trigger, sub-workflow call, form/chat rendering) replaced by an API route / UI; covered by API tests
  | 'SOURCE_DEFECT_NOT_REPRODUCED' // source behaviour is a defect; documented intent implemented instead
  | 'UNSUPPORTED';                 // explicitly out of scope (n8n editor scaffolding); reason in notes

export type TestRef = [file: string, title: string];
export interface Rule { workflow: string; nodes: string[] | RegExp; module: string; tests: TestRef[]; status: ParityStatus; io: string; notes?: string; }

const REG: TestRef = ['tests/regression.auth.test.ts', 'all AUTH source cases (parity regression)'];
const GOV = (title: string): TestRef => ['tests/governance.test.ts', title];
const PER = (title: string): TestRef => ['tests/persistence.test.ts', title];
const EVI = (title: string): TestRef => ['tests/evidence.test.ts', title];
const REV = (title: string): TestRef => ['tests/review-resubmission-status.test.ts', title];
const AGT = (title: string): TestRef => ['tests/agent-runtime.test.ts', title];
const CHT = (title: string): TestRef => ['tests/chat-audit.test.ts', title];
const API = (title: string): TestRef => ['tests/api.test.ts', title];
const E2E = (title: string): TestRef => ['tests/e2e/portal.spec.ts', title];

const utilityWorkflows = ['05', '06', '07A', '07B', '09', '10', '12'];
const utilityRules: Rule[] = utilityWorkflows.flatMap((workflow): Rule[] => [
  { workflow, nodes: ['When Executed by Another Workflow'], module: 'packages/workflows/src/super-agent.ts#createToolbox().call → utilities.ts#executeUtility', tests: [PER('exposes exactly the seven specialist tools')], status: 'REPLACED_BY_PLATFORM', io: 'in: {case_run_id, submission_version, processing_mode, persist_results}; out: n/a (sub-workflow call → in-process tool call)' },
  { workflow, nodes: ['Get Mock Utility Result'], module: 'packages/persistence/src/index.ts#findMockResult', tests: [REG, GOV('finalising from MOCK fixtures reproduces the source AUTH results')], status: 'PARITY_TESTED', io: 'in: case_run_id + check type; out: one dt_mock_utility_results row (Check_Type ILIKE = case-insensitive substring)', notes: workflow === '05' ? 'ILIKE substring semantics are required: AUTH-009 fixture row is DOCUMENT_EXTRACTION_AND_SECURITY and is returned to Workflow 05.' : undefined },
  { workflow, nodes: ['Get Decision Rules'], module: 'packages/persistence/src/index.ts#getRules', tests: [GOV('approves only when every mandatory check passes (FINAL-001)')], status: 'PARITY_TESTED', io: 'in: fixture Rule_IDs; out: dt_decision_rules rows' },
  { workflow, nodes: ['Build Utility Result'], module: 'packages/workflows/src/utilities.ts#buildResult / selectAppliedRule', tests: [REG, PER('returns the source-equivalent typed utility result fields')], status: 'PARITY_TESTED_DEVIATION', io: 'in: fixture row + rules; out: typed utility result (status, findings, reason_codes, rule_ids, is_terminal, terminal_outcome, prototype_data…)', notes: 'Source hard-codes submission_version=1; the target uses the requested version (AUTH-008-V2 is version 2). TBD rule → CTRL-001 preserved.' },
  { workflow, nodes: ['Store Utility Result'], module: 'packages/persistence/src/index.ts#upsertUtilityResult (unique index on case_run_id+submission_version+check_type)', tests: [PER('one utility cannot overwrite another utility'), PER('rerunning the same utility is idempotent')], status: 'PARITY_TESTED', io: 'in: utility result; out: dt_utility_results_runtime row upserted on the exact three-part key' },
  { workflow, nodes: ['Audit Utility Check'], module: 'packages/workflows/src/utilities.ts#executeUtility (UTILITY_CHECK_COMPLETED)', tests: [REG], status: 'PARITY_TESTED', io: 'in: utility result; out: dt_audit_events row UTILITY_CHECK_COMPLETED (stage = check_type)' },
  { workflow, nodes: ['Return Utility Result'], module: 'packages/workflows/src/super-agent.ts#utilityObservation', tests: [PER('returns the source-equivalent typed utility result fields')], status: 'PARITY_TESTED', io: 'in: built result; out: tool observation returned to SBO.02' },
]);

const rules: Rule[] = [
  ...utilityRules,

  // ---------------------------------------------------------------- 90 Finalize Decision
  { workflow: '90', nodes: ['Receive Finalization Request'], module: 'packages/governance/src/index.ts#finalizeDecision(repository, caseRunId, submissionVersion, resultSource)', tests: [GOV('finalising from MOCK fixtures reproduces the source AUTH results')], status: 'REPLACED_BY_PLATFORM', io: 'in: {case_run_id, submission_version, result_source}; out: n/a' },
  { workflow: '90', nodes: ['When clicking ‘Execute workflow’', 'Edit Fields', "Call '90 - Finalize Decision'"], module: 'n/a — n8n editor test scaffold (manual trigger → Set → self-call)', tests: [], status: 'UNSUPPORTED', io: 'manual test harness only', notes: 'Debug scaffolding for running Workflow 90 from the n8n editor; equivalent is the finalizeDecision unit/integration tests.' },
  { workflow: '90', nodes: ['Get Case'], module: 'packages/persistence#getCase', tests: [REG], status: 'PARITY_TESTED', io: 'in: case_run_id; out: dt_synthetic_cases row' },
  { workflow: '90', nodes: ['Prepare Result Source'], module: 'packages/governance/src/index.ts#parseResultSource', tests: [GOV('parses the result source like "Prepare Result Source"')], status: 'PARITY_TESTED', io: 'in: request; out: {case_run_id, submission_version, result_source ∈ MOCK|RUNTIME (default MOCK)}' },
  { workflow: '90', nodes: ['Select Result Source'], module: 'packages/governance/src/index.ts#parseResultSource / loadRowsForSource', tests: [GOV('parses the result source like "Prepare Result Source"')], status: 'PARITY_TESTED', io: 'in: result_source; out: branch MOCK | RUNTIME | error "Unsupported result source"' },
  { workflow: '90', nodes: ['Get Mock Utility Results', 'Package Mock Utility Results'], module: 'packages/governance/src/index.ts#loadRowsForSource (MOCK)', tests: [GOV('finalising from MOCK fixtures reproduces the source AUTH results')], status: 'PARITY_TESTED', io: 'in: case_run_id; out: utility rows from the static fixture table' },
  { workflow: '90', nodes: ['Get Runtime Utility Results', 'Package Runtime Utility Results'], module: 'packages/persistence#getRuntimeResults (superseded=false, one active row per check_type) → governance#loadRowsForSource (RUNTIME)', tests: [GOV('treats NOT_RUN rows as absent'), PER('seven checks remain seven unique check types for a clean case')], status: 'PARITY_TESTED', io: 'in: case_run_id + submission_version; out: normalised active rows, one per check_type' },
  { workflow: '90', nodes: ['Get Decision Rules'], module: 'packages/persistence#getRules', tests: [GOV('approves only when every mandatory check passes (FINAL-001)')], status: 'PARITY_TESTED', io: 'out: all dt_decision_rules rows' },
  { workflow: '90', nodes: ['Determine Final Decision'], module: 'packages/governance/src/index.ts#determineDecision', tests: [GOV('approves only when every mandatory check passes (FINAL-001)'), GOV('zero persisted runtime results → CTRL-002'), GOV('an explicit terminal business rule takes precedence'), GOV('a TBD rule can never produce an automated approval or rejection'), GOV('throws "Approval blocked"'), REG], status: 'PARITY_TESTED', io: 'in: case row, utility rows, rules; out: decision {outcome, primary_reason_code, target_queue, next_action, missing_information, conflicts, assumptions_used, completed_checks, checks_not_run, …}', notes: 'Deterministic; no LLM. Only addition: UNRESOLVED_SOURCE_GAP results route to CTRL-003 instead of the source throw.' },
  { workflow: '90', nodes: ['Get Communication Template'], module: 'packages/persistence#getTemplate', tests: [GOV('fills the exact source placeholders')], status: 'PARITY_TESTED', io: 'in: communication_template_id; out: dt_communication_templates row' },
  { workflow: '90', nodes: ['Build Communication'], module: 'packages/governance/src/index.ts#renderCommunication / fillTemplate', tests: [GOV('fills the exact source placeholders'), GOV('renders %s as a DRAFT with no unresolved placeholders')], status: 'PARITY_TESTED', io: 'in: decision + template; out: DRAFT communication (sent=false, approval_required=true)' },
  { workflow: '90', nodes: ['Store Final Decision'], module: 'packages/governance/src/index.ts#finalizeDecision (persistDecision)', tests: [GOV('writes decision, communication, runtime case and audit atomically')], status: 'PARITY_TESTED', io: 'in: decision; out: dt_decisions upsert (decision_id = DEC-{case}-{version})' },
  { workflow: '90', nodes: ['Store Initial Communication'], module: 'packages/governance/src/index.ts#finalizeDecision (persistCommunication)', tests: [GOV('is idempotent: finalising twice')], status: 'PARITY_TESTED', io: 'out: dt_communications upsert (COMM-{case}-V{version}-INITIAL, DRAFT)' },
  { workflow: '90', nodes: ['Prepare Runtime Case Record', 'Upsert Runtime Case'], module: 'packages/governance/src/index.ts#createRuntimeCase + persistRuntimeCase', tests: [REG], status: 'PARITY_TESTED', io: 'out: dt_cases_runtime upsert (status/current_stage from outcome map)', notes: 'Source column is synthetic_Only (case differs from other writers); the domain adapter normalises casing.' },
  { workflow: '90', nodes: ['Return Final Package'], module: 'packages/governance/src/index.ts#finalizeDecision return value', tests: [REG], status: 'PARITY_TESTED', io: 'out: {decision, communication}' },

  // ---------------------------------------------------------------- 91 Human Review Portal
  { workflow: '91', nodes: ['Open Review', 'Form'], module: 'apps/web/src/pages/ReviewPage.tsx + GET /api/reviews/:reviewId', tests: [API('serves the review package, completes once'), E2E('human review')], status: 'REPLACED_BY_PLATFORM', io: 'in: review id; out: review form with case/decision context (fields reviewer_name, reviewer_decision, reviewer_comments, override_reason)' },
  { workflow: '91', nodes: ['Get Review Record', 'Check Review Status', 'Review Found?', 'Review Open?'], module: 'packages/workflows/src/human-review.ts#getReviewPackage (PENDING | PENDING_REJECTION_CONFIRMATION are open)', tests: [REV('prevents duplicate completion'), REV('a review that is not found is reported without side effects')], status: 'PARITY_TESTED', io: 'in: review_id; out: found / open flags' },
  { workflow: '91', nodes: ['Review Not Found', 'Show Review Already Completed', 'Show Review Completed'], module: 'apps/web/src/pages/ReviewPage.tsx (REVIEW_NOT_FOUND / REVIEW_ALREADY_COMPLETED / result panel)', tests: [API('serves the review package, completes once'), E2E('human review')], status: 'REPLACED_BY_PLATFORM', io: 'form completion pages → HTTP 404/409 + UI messages' },
  { workflow: '91', nodes: ['Get Decision Record', 'Get Case Record', 'Prepare Review Package'], module: 'packages/workflows/src/human-review.ts#getReviewPackage', tests: [REV('creates a PENDING review for a non-remediable MANUAL_REVIEW')], status: 'PARITY_TESTED', io: 'out: review package (decision + case context)' },
  { workflow: '91', nodes: ['Validate Reviewer Submission'], module: 'packages/workflows/src/human-review.ts#completeHumanReview', tests: [REV('validates the reviewer submission like the source'), REV('changing a REJECT recommendation requires an override reason')], status: 'PARITY_TESTED', io: 'in: reviewer form; out: final decision config (APPROVE/NEED_MORE_INFORMATION/REJECT → queue, next action, template)' },
  { workflow: '91', nodes: ['Update Review Record'], module: 'packages/workflows/src/human-review.ts#completeHumanReview (persistReview)', tests: [REV('completes an open review exactly as source')], status: 'PARITY_TESTED', io: 'out: dt_human_reviews upsert status COMPLETED' },
  { workflow: '91', nodes: ['Update Final Decision'], module: 'packages/workflows/src/human-review.ts#completeHumanReview (persistDecision)', tests: [REV('completes an open review exactly as source')], status: 'PARITY_TESTED', io: 'out: dt_decisions upsert keeping decision_id, primary reason and created_at' },
  { workflow: '91', nodes: ['Get Human Review Communication Template', 'Build Human Review Communication', 'Store Human Review Communication'], module: 'packages/workflows/src/human-review.ts#completeHumanReview (COMM-{case}-V{version}-HUMAN)', tests: [REV('completes an open review exactly as source')], status: 'PARITY_TESTED', io: 'out: DRAFT communication (never sent)' },
  { workflow: '91', nodes: ['Prepare Reviewed Runtime Case', 'Update Runtime Case After Review'], module: 'packages/workflows/src/human-review.ts#completeHumanReview (persistRuntimeCase)', tests: [REV('completes an open review exactly as source')], status: 'SOURCE_DEFECT_NOT_REPRODUCED', io: 'out: dt_cases_runtime status/stage after review', notes: 'Source writes only human_review_required=false and a blank case_Run_ID; the prepared status/stage record is never persisted. Target persists the prepared record (docs/07 G-07).' },
  { workflow: '91', nodes: ['Create Review Audit Event'], module: 'packages/workflows/src/human-review.ts#completeHumanReview (HUMAN_REVIEW_COMPLETED)', tests: [REV('completes an open review exactly as source')], status: 'PARITY_TESTED', io: 'out: dt_audit_events HUMAN_REVIEW_COMPLETED' },
  { workflow: '91', nodes: ['Restore Reviewed Package'], module: 'packages/workflows/src/human-review.ts#completeHumanReview return value', tests: [API('serves the review package, completes once')], status: 'PARITY_TESTED', io: 'out: reviewed decision + communication' },

  // ---------------------------------------------------------------- 92 Resubmission Portal
  { workflow: '92', nodes: ['Open Resubmission'], module: 'apps/web/src/pages/ResubmissionPage.tsx + POST /api/resubmissions', tests: [API('performs a versioned resubmission'), E2E('resubmission')], status: 'REPLACED_BY_PLATFORM', io: 'in: {original_case_run_id, revised_case_run_id, resubmission_comments}' },
  { workflow: '92', nodes: ['Get Original Decision', 'Check Resubmission Eligibility', 'Resubmission Eligible?', 'Show Resubmission Not Allowed'], module: 'packages/workflows/src/resubmission.ts#createResubmission (RESUBMISSION_NOT_ALLOWED)', tests: [REV('requires the original decision to exist and blocks a second resubmission')], status: 'PARITY_TESTED', io: 'eligible only when the original decision outcome is NEED_MORE_INFORMATION' },
  { workflow: '92', nodes: ['Get Original Case', 'Get Revised Case', 'Validate Version Relationship', 'Version Relationship Valid?', 'Show Invalid Revised Version'], module: 'packages/workflows/src/resubmission.ts#createResubmission (INVALID_REVISED_VERSION)', tests: [REV('rejects %s → %s with %s and changes nothing')], status: 'PARITY_TESTED', io: 'same Case_ID, higher Submission_Version, different Case_Run_ID' },
  { workflow: '92', nodes: ['Prepare Revised Assessment', 'Run Revised SBO.02 Assessment', 'Restore Revised Decision'], module: 'packages/workflows/src/resubmission.ts → super-agent.ts#evaluateCase', tests: [REV('assesses the revised version, supersedes the original and records lineage')], status: 'PARITY_TESTED_DEVIATION', io: 'out: revised governed decision', notes: 'Source calls workflow "02 - SBO.02 - Profiling Super Agent", which is not in the upload; target runs the uploaded 03 orchestrator (docs/07 G-05).' },
  { workflow: '92', nodes: ['Prepare Original Case Supersede Update', 'Mark Original Case Superseded'], module: 'packages/workflows/src/resubmission.ts (SUPERSEDED_BY_RESUBMISSION / RESUBMITTED)', tests: [REV('assesses the revised version, supersedes the original and records lineage')], status: 'PARITY_TESTED', io: 'out: original dt_cases_runtime row status/stage/target_queue = revised case run' },
  { workflow: '92', nodes: ['Create Resubmission Audit Event'], module: 'packages/workflows/src/resubmission.ts (CASE_RESUBMITTED)', tests: [REV('assesses the revised version, supersedes the original and records lineage')], status: 'PARITY_TESTED', io: 'out: dt_audit_events CASE_RESUBMITTED' },
  { workflow: '92', nodes: ['Show Resubmission Result'], module: 'apps/web/src/pages/ResubmissionPage.tsx result panel', tests: [API('performs a versioned resubmission'), E2E('resubmission')], status: 'REPLACED_BY_PLATFORM', io: 'form completion → JSON + UI' },

  // ---------------------------------------------------------------- 95 Evidence Resolution Utility
  { workflow: '95', nodes: ['Receive Evidence Resolution Request'], module: 'packages/workflows/src/evidence.ts#resolveEvidence + POST /api/evidence/:id/resolve', tests: [API('accepted PDF evidence flows through resolution and resumes the assessment'), ['tests/security.test.ts', 'three parallel resolves make exactly one model call']], status: 'REPLACED_BY_PLATFORM', io: 'in: {evidence_request_id, case_run_id, submission_version}', notes: 'Runs as one atomic step under a row lock (docs/07 G-28): parallel calls cannot double-spend an attempt or resume twice.' },
  { workflow: '95', nodes: ['Get Evidence Request', 'Check Resolution Request', 'Resolution Request Valid?', 'Stop Invalid Resolution Request'], module: 'packages/workflows/src/evidence.ts#resolveEvidence (exact request/case/version/status checks)', tests: [EVI('resolution enforces case and submission-version equality with the stored row')], status: 'PARITY_TESTED', io: 'valid only for RECEIVED | PARTIALLY_RECEIVED | INSUFFICIENT with matching case + version' },
  { workflow: '95', nodes: ['Get Evidence Records', 'Check Evidence Records', 'Evidence Records Exist?', 'Stop and Error'], module: 'packages/workflows/src/evidence.ts#resolveEvidence (EVIDENCE_RECORDS_NOT_FOUND)', tests: [EVI('resolution needs a RECEIVED/PARTIALLY_RECEIVED/INSUFFICIENT request'), EVI('keeps the request open, records EVID-002')], status: 'PARITY_TESTED_DEVIATION', io: 'active = not REJECTED/SUPERSEDED; earlier INSUFFICIENT records stay in scope (cumulative)', notes: 'Target hardening: also requires at least one newly RECEIVED record so no attempt is consumed without new evidence.' },
  { workflow: '95', nodes: ['Get Evidence Case', 'Prepare Resolution Context'], module: 'packages/workflows/src/evidence.ts#resolveEvidence (evidence_request, case_context, evidence_records)', tests: [EVI('passes evidence to the model only as JSON data')], status: 'PARITY_TESTED', io: 'out: context JSON for the model' },
  { workflow: '95', nodes: ['Resolve Additional Evidence'], module: 'packages/agent-runtime/src/index.ts#ClaudeAgentRuntime.resolveEvidence + renderEvidenceResolutionPrompt', tests: [AGT('SBO.02 system message, user template, structuring prompt and evidence prompt match'), AGT('sends the evidence prompt with no tools available to the model')], status: 'PARITY_TESTED_DEVIATION', io: 'in: exact source prompt + context; out: structured resolution', notes: 'Model provider changes from OpenAI gpt-5-mini to the Claude Agent SDK (model from CLAUDE_MODEL); prompt text is byte-identical.' },
  { workflow: '95', nodes: ['OpenAI Model - Evidence Resolution', 'OpenAI Model - Evidence Parser Repair'], module: 'packages/agent-runtime/src/index.ts#ClaudeAgentRuntime (CLAUDE_MODEL)', tests: [AGT('registers exactly the seven specialist tools, least-privilege options')], status: 'PARITY_TESTED_DEVIATION', io: 'language model', notes: 'Provider substitution (OpenAI → Claude); model name is an environment variable, never hard-coded.' },
  { workflow: '95', nodes: ['Structured Evidence Resolution Parser', 'Auto-fix Evidence Resolution Output'], module: 'packages/domain/src/index.ts#EvidenceResolutionWireSchema (Zod)', tests: [AGT('rejects %s'), EVI('malformed model output is a system error')], status: 'PARITY_TESTED_DEVIATION', io: 'schema: resolution_status, resolved, supported_facts, remaining_gaps, reason_codes, recommended_next_action, confidence', notes: 'Strict Zod validation replaces LLM auto-fix. Invalid output is a system error that consumes no customer attempt (source coerced unknown statuses to INSUFFICIENT).' },
  { workflow: '95', nodes: ['Build Resolved Utility Result'], module: 'packages/workflows/src/evidence.ts#materializeResolution', tests: [EVI('keeps the request open, records EVID-002'), EVI('escalates on the third insufficient attempt'), EVI('escalates to a MANUAL_REVIEW evidence review')], status: 'PARITY_TESTED', io: 'out: utility result (EVID-001 PASS | EVID-002 INCONCLUSIVE NMI | EVID-003 INCONCLUSIVE MANUAL_REVIEW) + request status' },
  { workflow: '95', nodes: ['Store Resolved Utility Result'], module: 'packages/workflows/src/evidence.ts#resolveEvidence (upsertUtilityResult on the originating check)', tests: [PER('evidence resolution intentionally replaces only the originating check')], status: 'PARITY_TESTED', io: 'out: dt_utility_results_runtime upsert on exact key' },
  { workflow: '95', nodes: ['Update Evidence Record Status'], module: 'packages/workflows/src/evidence.ts#resolveEvidence (only RECEIVED records change)', tests: [EVI('keeps the request open, records EVID-002')], status: 'PARITY_TESTED', io: 'RECEIVED → ACCEPTED | CONTRADICTORY | INSUFFICIENT' },
  { workflow: '95', nodes: ['Update Evidence Request'], module: 'packages/workflows/src/evidence.ts#resolveEvidence (status, attempt_count, received_at, resolved_at)', tests: [EVI('escalates on the third insufficient attempt')], status: 'PARITY_TESTED', io: 'ACCEPTED | INSUFFICIENT | ESCALATED with attempt_count+1' },
  { workflow: '95', nodes: ['Audit Evidence Resolution'], module: 'packages/workflows/src/evidence.ts#resolveEvidence (ADDITIONAL_EVIDENCE_REQUIRED)', tests: [EVI('keeps the request open, records EVID-002')], status: 'PARITY_TESTED', io: 'out: dt_audit_events (source event name preserved)' },
  { workflow: '95', nodes: ['Return Resolution Result'], module: 'packages/workflows/src/evidence.ts#resolveEvidence return value', tests: [API('accepted PDF evidence flows through resolution and resumes the assessment')], status: 'PARITY_TESTED', io: 'out: resolution result for Workflow 03 routing' },

  // ---------------------------------------------------------------- 96 Customer Evidence Upload Portal
  { workflow: '96', nodes: ['Open Evidence Upload'], module: 'apps/web/src/pages/UploadPage.tsx + GET/POST /api/evidence/:id[/upload]', tests: [API('validates the evidence request for the upload page'), E2E('evidence upload')], status: 'REPLACED_BY_PLATFORM', io: 'in: hidden evidence_request_id, case_run_id; fields evidence_type, evidence_notes, evidence_file (.pdf)' },
  { workflow: '96', nodes: ['Normalise Evidence Upload Input', 'Get Evidence Request'], module: 'apps/api/src/app.ts upload route + evidence.ts#validateEvidenceRequest', tests: [API('validates the evidence request for the upload page')], status: 'PARITY_TESTED', io: 'stored request row is authoritative for case identity' },
  { workflow: '96', nodes: ['Validate Evidence Request', 'Request Open?'], module: 'packages/workflows/src/evidence.ts#validateEvidenceRequest', tests: [EVI('a supplied case id that differs from the stored row is rejected'), EVI('rejects statuses that do not permit submission')], status: 'PARITY_TESTED', io: 'reasons: EVIDENCE_REQUEST_ID_NOT_SUPPLIED | …NOT_FOUND | …ID_MISMATCH | CASE_RUN_ID_NOT_AVAILABLE | CASE_RUN_ID_MISMATCH | EVIDENCE_REQUEST_NOT_OPEN' },
  { workflow: '96', nodes: ['Show Upload Not Allowed', 'Show Unreadable PDF', 'Show Upload Completed'], module: 'apps/web/src/pages/UploadPage.tsx (result panels)', tests: [API('rejects %s and leaves the request OPEN with nothing stored'), E2E('evidence upload')], status: 'REPLACED_BY_PLATFORM', io: 'form completion pages → HTTP 4xx/200 + UI messages' },
  { workflow: '96', nodes: ['Extract PDF Text', 'Check Extracted PDF', 'PDF Text Available?'], module: 'apps/api/src/pdf.ts#extractPdfText + evidence.ts#submitUploadedEvidence (≥ 20 characters)', tests: [API('accepts a real text PDF, stores the original'), EVI('unreadable PDF (< 20 characters)'), ['tests/security.test.ts', 'refuses a page bomb from its declared page count']], status: 'PARITY_TESTED_DEVIATION', io: 'text extraction; unreadable PDF keeps the request open', notes: 'n8n Extract From File replaced by unpdf (pdf-parse@1.x fails on every PDF under Node 24), run in a worker thread with timeout, page cap (50) and output cap; hostile PDFs answer PDF_TOO_COMPLEX (docs/07 G-23, G-29).' },
  { workflow: '96', nodes: ['Prepare Uploaded Evidence', 'Store Uploaded Evidence'], module: 'packages/workflows/src/evidence.ts#submitUploadedEvidence', tests: [EVI('accepts extracted PDF text ≥ 20 characters and records file metadata')], status: 'PARITY_TESTED_DEVIATION', io: 'out: dt_case_evidence row RECEIVED (FILE_UPLOAD)', notes: 'Source leaves storage_url empty (file discarded); target preserves the original file under a generated name outside any web root and records it.' },
  { workflow: '96', nodes: ['Mark Uploaded Evidence Received'], module: 'packages/workflows/src/evidence.ts#receiveEvidence', tests: [EVI('accepts extracted PDF text ≥ 20 characters and records file metadata')], status: 'PARITY_TESTED', io: 'out: dt_evidence_requests status RECEIVED, received_at' },
  { workflow: '96', nodes: ['Audit Uploaded Evidence Received'], module: 'packages/workflows/src/evidence.ts#receiveEvidence (ADDITIONAL_EVIDENCE_RECEIVED)', tests: [EVI('accepts extracted PDF text ≥ 20 characters and records file metadata')], status: 'PARITY_TESTED', io: 'out: dt_audit_events (reason CUSTOMER_FILE_EVIDENCE_RECEIVED)' },

  // ---------------------------------------------------------------- 03 SBO.02 Agentic Reasoning Orchestrator
  { workflow: '03', nodes: ['Agentic Chat'], module: 'apps/web/src/pages/ChatPage.tsx + POST /api/chat, /api/cases/:id/{evaluate,messages}', tests: [API('evaluates AUTH-001 and returns only curated business output'), E2E('chat')], status: 'REPLACED_BY_PLATFORM', io: 'in: chat message + session id; out: curated reply' },
  { workflow: '03', nodes: ['Resolve Case Request', 'Case ID Present?', 'Prepare Invalid Request Response'], module: 'packages/workflows/src/super-agent.ts#resolveCaseRequest + chat.ts', tests: [CHT('rejects messages without a case id and unknown cases without running an assessment')], status: 'PARITY_TESTED', io: 'regex AUTH-\\d{3}(-V\\d+)?; version from -Vn suffix' },
  { workflow: '03', nodes: ['Get Case Context', 'Check Case Exists', 'Case Exists?', 'Prepare Case Not Found Response'], module: 'packages/workflows/src/chat.ts#handleChatMessage', tests: [CHT('rejects messages without a case id and unknown cases without running an assessment')], status: 'PARITY_TESTED', io: 'unknown case → "was not found. No assessment was performed."' },
  { workflow: '03', nodes: ['Reset Runtime Utility Results'], module: 'packages/workflows/src/super-agent.ts#evaluateCase (deleteRuntimeResults)', tests: [PER('the chat-entry reset deletes only the exact'), PER('re-evaluating a case resets first'), ['tests/security.test.ts', 'refuses re-evaluation after a human review is completed']], status: 'PARITY_TESTED_DEVIATION', io: 'deletes rows for exactly case_run_id + submission_version; bypassed on evidence resume', notes: 'Target hardening (docs/07 G-27): a case whose review is COMPLETED, or that is SUPERSEDED_BY_RESUBMISSION, is locked (CASE_LOCKED) because the source lets any chat message wipe and overwrite a human-reviewed decision. The whole reset + assessment + finalization runs in one transaction.' },
  { workflow: '03', nodes: ['Get Existing Runtime Results', 'Prepare Agent Context'], module: 'packages/workflows/src/super-agent.ts#prepareAgentContext', tests: [AGT('prompt context reports INITIAL vs RESUMED')], status: 'PARITY_TESTED', io: 'out: assessment_cycle, next_required_check, completed/pending checks, evidence_resolved_checks, case_context, existing_runtime_results' },
  { workflow: '03', nodes: ['SBO.02 Agentic Reasoning Super Agent'], module: 'packages/agent-runtime/src/index.ts#ClaudeAgentRuntime.runSuperAgent (Claude Agent SDK + in-process MCP tools)', tests: [AGT('registers exactly the seven specialist tools, least-privilege options'), AGT('an LLM that stops early and recommends APPROVE')], status: 'PARITY_TESTED_DEVIATION', io: 'in: exact source system message + user template; tools: seven specialist utilities; out: provisional recommendation only', notes: 'OpenAI agent → Claude Agent SDK. Prompt text byte-identical; tools are guarded by the governed toolbox.' },
  { workflow: '03', nodes: ['OpenAI Model - Agent Reasoning', 'OpenAI Model - Output Structuring', 'OpenAI Model - Parser Repair'], module: 'packages/agent-runtime/src/index.ts (CLAUDE_MODEL)', tests: [AGT('registers exactly the seven specialist tools, least-privilege options')], status: 'PARITY_TESTED_DEVIATION', io: 'language model', notes: 'Provider substitution; model from environment.' },
  { workflow: '03', nodes: /^Tool - /, module: 'packages/workflows/src/super-agent.ts#createToolbox (tool descriptions from sbo02-tools.json)', tests: [AGT('tool descriptions match the seven Workflow 03 tool nodes'), PER('refuses to skip an incomplete earlier check and persists nothing')], status: 'PARITY_TESTED', io: 'tool → specialist utility (05/06/07A/07B/12/09/10)' },
  { workflow: '03', nodes: ['Prepare Parsing Input', 'Structure Agent Recommendation', 'Structured Output Parser', 'Auto-fix Recommendation Format', 'Normalise Provisional Recommendation'], module: 'packages/agent-runtime/src/index.ts#renderStructuringPrompt + normalizeProvisional (Zod ProvisionalWireSchema)', tests: [AGT('an invalid provisional outcome is normalised to MANUAL_REVIEW'), AGT('unparseable structured output falls back')], status: 'PARITY_TESTED_DEVIATION', io: 'out: provisional recommendation {tools_called, provisional_outcome, evidence_summary, missing_information, conflicts, human_review_required, next_action, decision_rationale, confidence}', notes: 'Visible trace comes from the harness (authoritative); unparseable output degrades to a MANUAL_REVIEW provisional instead of failing the run.' },
  { workflow: '03', nodes: ['Prepare Runtime Finalization Input', 'Run Governed Runtime Finalizer'], module: 'packages/workflows/src/super-agent.ts#runAssessment → governance#finalizeDecision(RUNTIME)', tests: [REG, AGT('an LLM that stops early and recommends APPROVE')], status: 'PARITY_TESTED', io: 'persisted runtime results exist before the Finalizer runs' },
  { workflow: '03', nodes: ['Compare Agent and Governed Outcome'], module: 'packages/workflows/src/super-agent.ts#runAssessment (governance_override)', tests: [AGT('an LLM that forces APPROVE on an inactive business is overridden to REJECT')], status: 'PARITY_TESTED', io: 'out: provisional vs governed outcome + override message' },
  { workflow: '03', nodes: ['Build Chat Response'], module: 'packages/workflows/src/chat-response.ts#buildChatResponse', tests: [CHT('AUTH-001 returns a curated business response'), CHT('is explained in customer-safe language')], status: 'PARITY_TESTED', io: 'curated markdown; never raw prompts/tool JSON/rules', notes: 'Source glyphs are mojibake in the export; intended glyphs used.' },
  { workflow: '03', nodes: ['Final Chat Response', 'Conversation Memory'], module: 'apps/api/src/app.ts (chat_sessions via ChatSessionState) + packages/workflows/src/chat.ts', tests: [CHT('conversation state is per session'), API('keeps one server-issued conversation session across requests')], status: 'REPLACED_BY_PLATFORM', io: 'buffer memory (20) + chat responses → persisted session state and JSON messages' },
  { workflow: '03', nodes: ['Classify Continuation Requirement', 'Customer Evidence Required?'], module: 'packages/workflows/src/super-agent.ts#classifyContinuation', tests: [CHT('classifies continuation exactly as the source table')], status: 'PARITY_TESTED', io: 'reason → {remediable, channel, originating check, requested items}' },
  { workflow: '03', nodes: ['Create Evidence Request', 'Upsert row(s)', 'Update Case to Waiting for Evidence'], module: 'packages/workflows/src/super-agent.ts#createEvidenceRequest', tests: [EVI('AUTH-003 creates an OPEN request for the originating AUTHORITY_VALIDATION gap')], status: 'PARITY_TESTED', io: 'EVID-{case}-V{version}-{ms}, OPEN, max_attempts 3, due +48h; case → WAITING_FOR_EVIDENCE / CUSTOMER_EVIDENCE / CUSTOMER_FOLLOW_UP' },
  { workflow: '03', nodes: ['Select Evidence Channel', 'Route Selected Method'], module: 'packages/workflows/src/chat.ts#presentAssessment / handleChatMessage', tests: [CHT('AUTH-002 (file evidence) goes straight to the upload prompt'), CHT('AUTH-003: asks TEXT or UPLOAD')], status: 'PARITY_TESTED', io: 'CHAT_TEXT | FILE_UPLOAD | CHAT_OR_FILE' },
  { workflow: '03', nodes: ['Ask Customer for Evidence Method', 'Normalise Evidence Method', 'Evidence Method Valid?', 'Ask Evidence Method Again', 'Normalise Retry Method', 'Retry Method Valid?', 'Send Method Selection Failed'], module: 'packages/workflows/src/chat.ts#normaliseEvidenceMethod / handleChatMessage', tests: [CHT('method selection: one retry prompt'), CHT('normalises evidence-method replies like the source')], status: 'PARITY_TESTED', io: 'TEXT|CHAT|PASTE|TYPE / UPLOAD|FILE|DOCUMENT|PDF; one retry then failure message' },
  { workflow: '03', nodes: ['Ask for Text Evidence', 'Normalise Customer Text Evidence', 'Text Evidence Received?', 'Ask for Text Evidence Again'], module: 'packages/workflows/src/chat.ts (AWAITING_TEXT)', tests: [CHT('TEXT path: empty input asks again')], status: 'PARITY_TESTED', io: 'CANCEL|STOP|END|CANCEL REQUEST cancel; empty asks again' },
  { workflow: '03', nodes: ['Prepare Text Evidence Record', 'Store Text Evidence', 'Mark Text Evidence Received', 'Audit Text Evidence Received'], module: 'packages/workflows/src/evidence.ts#submitTextEvidence', tests: [EVI('stores RECEIVED evidence, marks the request RECEIVED')], status: 'PARITY_TESTED', io: 'out: evidence row + request RECEIVED + ADDITIONAL_EVIDENCE_RECEIVED' },
  { workflow: '03', nodes: ['Customer Cancelled', 'Cancel Evidence Request', 'Send Cancellation Message'], module: 'packages/workflows/src/evidence.ts#cancelEvidenceRequest + chat.ts', tests: [EVI('cancels the request, updates the case'), CHT('TEXT path: empty input asks again')], status: 'PARITY_TESTED_DEVIATION', io: 'request CANCELLED', notes: 'Source text-path cancel updates only the request; target applies the upload-path behaviour (case → EVIDENCE_REQUEST_CANCELLED + audit) to both (docs/07 G-09).' },
  { workflow: '03', nodes: ['Build Evidence Upload Link', 'Ask for Evidence Upload', 'Normalise Upload Reply', 'Get Uploaded Evidence', 'Evaluate Upload Availability', 'Evidence Available?', 'Ask Customer to Complete Upload'], module: 'packages/workflows/src/chat.ts (AWAITING_UPLOAD) + uploadUrlFor', tests: [CHT('UPLOAD path: "UPLOADED" without a stored upload')], status: 'PARITY_TESTED_DEVIATION', io: 'upload link with evidence_request_id + case_run_id; any non-cancel reply checks for uploaded evidence', notes: 'Upload link points at the target web app (APP_BASE_URL) instead of the n8n form URL; "available" requires a newly RECEIVED record.' },
  { workflow: '03', nodes: ['Customer Cancelled Upload?', 'Cancel Upload Request', 'Update Cancelled Case', 'Audit Upload Cancellation', 'Send Upload Cancelled'], module: 'packages/workflows/src/evidence.ts#cancelEvidenceRequest + chat.ts', tests: [CHT('UPLOAD path: CANCEL cancels the request'), EVI('cancels the request, updates the case')], status: 'PARITY_TESTED', io: 'request CANCELLED; case EVIDENCE_REQUEST_CANCELLED / CUSTOMER_EVIDENCE / CUSTOMER_FOLLOW_UP; audit EVIDENCE_REQUEST_CANCELLED' },
  { workflow: '03', nodes: ['Resolve Customer Evidence'], module: 'packages/workflows/src/evidence.ts#resolveEvidenceAndContinue', tests: [EVI('source-faithful AUTH-003: EVID-001 resumes')], status: 'PARITY_TESTED', io: 'calls Workflow 95 with the stored request' },
  { workflow: '03', nodes: ['Route Evidence Resolution'], module: 'packages/workflows/src/evidence.ts#resolveEvidenceAndContinue', tests: [EVI('escalates to a MANUAL_REVIEW evidence review')], status: 'SOURCE_DEFECT_NOT_REPRODUCED', io: 'RESOLVED | PARTIAL | INSUFFICIENT | CONTRADICTORY', notes: 'Source switch compares against the misspelled literal "CONTRADITORY", so a CONTRADICTORY result matches no branch. Target implements the documented EVID-003 route (docs/07 G-04).' },
  { workflow: '03', nodes: ['Update row(s)', 'Send Evidence Accepted Message'], module: 'packages/workflows/src/super-agent.ts#resumeAssessment + chat.ts#afterResolution', tests: [EVI('sets the runtime case to ASSESSMENT_RESUMED / AGENTIC_REASSESSMENT before the resumed assessment finalises'), CHT('AUTH-003: asks TEXT or UPLOAD')], status: 'PARITY_TESTED', io: 'case → ASSESSMENT_RESUMED / AGENTIC_REASSESSMENT / SBO.02; message; resume from next incomplete check (no reset)' },
  { workflow: '03', nodes: ['If', 'Explain Remaining Evidence Gap'], module: 'packages/workflows/src/chat.ts#afterResolution (RETRY)', tests: [CHT('insufficient evidence explains the remaining gap and re-asks')], status: 'PARITY_TESTED', io: 'retry_allowed → explain gaps and re-ask; else escalate' },
  { workflow: '03', nodes: ['Create Evidence Review After Max Attempts', 'Update Case After Evidence Escalation', 'Audit Evidence Escalation', 'Send Evidence Escalation Message'], module: 'packages/workflows/src/evidence.ts#escalateToEvidenceReview (NEED_MORE_INFORMATION)', tests: [EVI('escalates on the third insufficient attempt')], status: 'PARITY_TESTED', io: 'REV-{case}-EVIDENCE-{version}; case REVIEW_PENDING / HUMAN_REVIEW / EVIDENCE_REVIEW; audit EVIDENCE_REVIEW_QUEUED' },
  { workflow: '03', nodes: ['Create Contradictory Evidence Review', 'Update Contradictory Evidence Case', 'Audit Contradictory Evidence', 'Send Contradictory Evidence Message'], module: 'packages/workflows/src/evidence.ts#escalateToEvidenceReview (MANUAL_REVIEW)', tests: [EVI('escalates to a MANUAL_REVIEW evidence review'), CHT('contradictory evidence routes to a human evidence reviewer')], status: 'SOURCE_DEFECT_NOT_REPRODUCED', io: 'REV-{case}-EVIDENCE-{version}; audit CONTRADICTORY_EVIDENCE_ESCALATED', notes: 'Unreachable in the source because of the misspelled switch key; implemented per documented intent.' },
];

export default rules;
